### PR TITLE
Adding cross run checks

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Trying to solve #34

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/42)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[index.html, line 104 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jQCvDViS9vO8vZdHQ:-K6jQCvEhGudhiAw9bTv:1876238722) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/index.html#L104)):_
So what happens if you call a run `PASS`? Seems like it could be worth giving the statuses a prefix and not allowing run names to have that prefix, or something.

---

_[LovefieldService.js, line 316 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jRzag6Ezk6jSGjJYm:-K6jRzahj5qXHpFV88E9:-1328582436) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L316)):_
So I think this can lead to us joining in the results for each run multiple times, which I think is unnecessary. We should probably create a object `{runName: [resultsTableAlias¸ runTableAlias]}` and then do all the joins iterating over that object (using `Object.keys`) 

---

_[LovefieldService.js, line 356 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jSyLQgzPQoDrBuFYA:-K6jSyLRGhJC9opWhjXs:-624730150) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L356)):_
You could reduce the amount of duplication with the code above here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by martiansideofthemoon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[index.html, line 104 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jQCvDViS9vO8vZdHQ:-K6lQ75m-cC5y9xf1wMY:-1391005899) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/index.html#L104)):_
I didn't quite get you here. If we call a run `PASS`, all tests having the `PASS` result for that run will come right?

---

_[LovefieldService.js, line 316 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jRzag6Ezk6jSGjJYm:-K6lQVTUb9phnfoF0AbD:-350647821) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L316)):_
Yeah I was thinking about this scheme but I am not very sure about the SQL query in this case. The query currently says 
`query = query.innerJoin(alias, results[i].run_id.eq(alias.run_id));`
We would need to add a condition saying `alias.name.eq(runName)`. Can we add this second condition to a `JOIN` using `WHERE`?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[index.html, line 104 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jQCvDViS9vO8vZdHQ:-K6mmDQ09cnKpSEvEjjr:-1723414248) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/index.html#L104)):_
I mean if the run is called `PASS` you have two options with value `PASS` so everything else becomes ambiguous. Thinking about it some more, perhaps the best option would be

```
        <option ng-repeat="run in runs" value="run-{{ run.name }}">Result from {{ run.name }}</option>
```

Oh and you probably want to exclude the current run as an option because it never makes any sense. That's a bit harder of course because the options here need to be set dynamically after the run is chosen. But not much harder I think.

---

_[LovefieldService.js, line 316 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jRzag6Ezk6jSGjJYm:-K6mnLDtmkpdC7PiMp2U:1581279306) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L316)):_
I don't understand the question.

At the moment you can end up doing something like

```
JOIN results AS results_1 ON results.test_id = tests.id
JOIN runs AS runs_1 ON runs_1.run_id = results_1.run_id
WHERE runs_1.name = 'foo'
JOIN results AS results_2_a ON results.test_id = tests.id
JOIN runs AS runs_2_a ON runs_2_a.run_id = results_2_a.run_id
WHERE runs_2_a.name = 'foo'
```

Which seems rather pointless because we only want one set of columns from each run, and it never makes sense to compare a run's results to itself (even if it did something like `result_1 = result_1` would make just as much sense as any alternative).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[LovefieldService.js, line 316 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jRzag6Ezk6jSGjJYm:-K6obzDV9S-5erl9L-0f:-21704396) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L316)):_
So posting the problem as I understand it here.
I have 2 log files, having completely different tests. Ideally, on running a left outer join, the tests of the first run should have a `NULL` result row for the results of the second run. So I removed all `WHERE` clauses, and ordered by `test_id` to get an output (only test_id) of the form 1,2,3,4,5,6... I was expecting something like 1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4... (which is what I get when the test has results for both runs). 

My exact query was the one you've typed here - https://github.com/google/lovefield/issues/123 without the `WHERE` clause.

 So I conclude that either my understanding of `LEFT OUTER JOIN` is incorrect, or the fact that we have more than one `LEFT OUTER JOIN` is causing an error.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[LovefieldService.js, line 316 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6jRzag6Ezk6jSGjJYm:-K6ohbWj25GwL5YJ4cJb:1977250067) ([raw file](https://github.com/jgraham/wptview/blob/7e3e6dee47d34652becc7ce435d8e1af5e620f7e/LovefieldService.js#L316)):_
I suspect that `LEFT OUTER JOIN` doesn't work as I expect in general. I tinkered the code to create a case where I just have one run loaded and tests from an old run still present. On doing a `LEFT OUTER JOIN` I failed to get those old tests with NULL entries. (which don't have a result in this run).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by jgraham** [comment]
I added a commit in https://github.com/jgraham/wptview/tree/pr/42 which afaik fixes this

**Comment by martiansideofthemoon** [comment]
@jgraham, the same problem persists. But the current scheme of doing things is a lot cleaner imo

**Comment by jgraham** [comment]
Can you provide an example that didn't work? When I tried with a three files, two with the same tests and one with different tests the things I tried seem to work.

**Comment by martiansideofthemoon** [comment]
@jgraham: I think I had checked out the wrong branch. Works like a charm :smile: Need some help with the `pull` though. Getting an error as mentioned in the other PR

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r2.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[LovefieldService.js, line 301 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/42#-K6tBILjFS25NAP--HnI:-K6tBILjFS25NAP--HnJ:1823868902) ([raw file](https://github.com/jgraham/wptview/blob/27d44c53cf87661f4ba42ff76636801982588e57/LovefieldService.js#L301)):_
Missing `;`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/42)_

**Pull request merged**
