### PR TITLE
Added warnings UI

### PR DESCRIPTION
**Pull request by arpan98**
Tries to solve #29 
Changed the warnings data structure to correspond to each run individually. Had to implement a slight workaround by saving the temporary data because [like here](https://github.com/mozilla/wptview/blob/master/angular_scripts.js#L379), `updateRuns()` is called after the entire run process has been ended. Also made a tooltip on a exclamation mark beside the run name to show the number of warnings. I was unable to find more than one log with warnings, so I have not yet tested the individual-run-warnings feature. Please link any logs you find with warnings.
Also, need some details as to what UI is to be shown when the exclamation mark is clicked.
Have a look @martiansideofthemoon @jgraham 

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/wptview/142)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
The fix fails when you have > 1 log file. Try this https://drive.google.com/file/d/0B5Y_SiDYwIOba2FYd25TQ1N3NmM/view?usp=sharing

**Comment by arpan98** [comment]
The problem arises because the warnings list is not committed to the database. So, every time `getRuns` command is passed, the data is received from the database again and the warnings list is lost. Hence, on adding multiple log files, all warnings of previously imported files are lost.

Any suggestions on what to do here? @martiansideofthemoon @jgraham We could save the warnings list to the database as a JSON string, that is one way.

**Comment by jgraham** [comment]
Yeah, if we want to display these, they should be saved to the database in some way. I guess given the relative slowness of LoveField, just saving a single string might make more sense than creating a warnings table, which would be my natural instinct here.

**Comment by arpan98** [comment]
The string would be quite large though, for example the log file linked by @martiansideofthemoon has 570 warnings, that is, 570 `duplicate` objects.

**Comment by jgraham** [comment]
I'm not too worried about it being large since the data here is generally rather large.

**Comment by arpan98** [comment]
@jgraham @martiansideofthemoon Have a look at the fix. It works for multiple runs. Need some guidelines for the UI for displaying the warnings.

**Comment by martiansideofthemoon** [comment]
Good effort! I couldn't get it to work due to the error mentioned though :cry: 

<details><summary>

<i>Previously, arpan98 (Arpan Banerjee) wrote…</i></summary>



> @jgraham @martiansideofthemoon Have a look at the fix. It works for multiple runs. Need some guidelines for the UI for displaying the warnings.
> </details>

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[angular_scripts.js, line 266 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJUopl7XhV8KJoDCfdI:-KJUopl8UkLKq5DcK_d3:1074332302) ([raw file](https://github.com/mozilla/wptview/blob/3842610055a0b49ff509e4c2df9199408320b7b1/angular_scripts.js#L266)):_

> ``` JavaScript
>           run.edit = false;
>           run.newName = "";
>           run.warnings = JSON.parse(run.warnings);
> ```

There seems to be a problem here as `run.warnings` is `undefined` in [this](http://localhost:8000/#/?urls=http:%2F%2Fmozilla-releng-blobs.s3.amazonaws.com%2Fblobs%2Fmozilla-inbound%2Fsha512%2F0a62ad814642e61bedbadd946ac2a2519373fd70718b1425be7702f95439579f2776841f1a9d65326d29818bd5de4c2d2ff769bfc6cbe735f75a8c03708b2cec,Rev7%20MacOSX%20Yosemite%2010.10.5%20mozilla-inbound%20debug%20test%20web-platform-tests-e10s-8) query string.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142#-:-KJUpb-kPWDpCk3dFlDK:68520627)_

**Comment by martiansideofthemoon** [comment]
Sorry my bad, didn't delete the old database. Perhaps a user could click on the warnings icon and get a list of warnings in the bottom panel we have? (https://github.com/mozilla/wptview/blob/master/index.html#L161)

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> Good effort! I couldn't get it to work due to the error mentioned though :cry: 
> </details>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[angular_scripts.js, line 332 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJUwCbxWHgEkQae9Rb3:-KJUwCbyGOw4NXES27Yy:-1457956555) ([raw file](https://github.com/mozilla/wptview/blob/3842610055a0b49ff509e4c2df9199408320b7b1/angular_scripts.js#L332)):_

> ``` JavaScript
>   function saveWarnings(runName, duplicates) {
>     return resultsModel.updateWarnings(runName, duplicates)
>       .then(() => {console.log("Updated warnings.");});
> ```

You don't need a `saveWarnings` function.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142#-:-KJUwZVTYHGt_RgTVT43:-224871369)_

**Comment by martiansideofthemoon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[wptview.css, line 121 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJUyPS8PeyxiwK0ZRwh:-KJUyPS93J71zqPX2fDd:155189179) ([raw file](https://github.com/mozilla/wptview/blob/3842610055a0b49ff509e4c2df9199408320b7b1/wptview.css#L121)):_

> ``` CSS
>     padding: 5px 0;
>     border-radius: 6px;
> 
> ```

remove this space

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142)_

**Comment by arpan98** [comment]
On clicking the icon, I'm showing the list in the `detailsPanel`. Have a look @jgraham @martiansideofthemoon

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r2, 3 of 4 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

_[angular_scripts.js, line 288 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkee-aq6qapPbtTm5s:-KJkee-bF8BCwBEkql0t:-515359571) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/angular_scripts.js#L288)):_

> ``` JavaScript
>     .then((duplicates) => {
>       return resultsModel.updateWarnings(name, duplicates)
>       .then(() => {console.log("Updated warnings.");});
> ```

Don't need the `console.log` here.

---

_[angular_scripts.js, line 553 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkelXPkLVUKoXnD0PH:-KJkelXPkLVUKoXnD0PI:1831479376) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/angular_scripts.js#L553)):_

> ``` JavaScript
>   $scope.showWarnings = function(run) {
>     $scope.displayWarnings.runName = run.name;
>     $scope.displayWarnings.warnings = angular.copy(run.warnings);
> ```

Why is making a copy required?

---

_[index.html, line 25 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkeTjwoLbubaiTzzDV:-KJkeTjxB4h_Uj1UKJBb:-2058414018) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/index.html#L25)):_

> ``` HTML
>             <th></th>
>             <th>Run Name</th>
>             <th ng-show="runs | warningFilter"></th>
> ```

I would make this the last column and show it always.

---

_[index.html, line 41 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkbudA46Swz7z6MGNH:-KJkbudB0nsNUUMavet0:233847772) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/index.html#L41)):_

> ``` HTML
>             <td>
>               <div class="tooltip" ng-show="run.warnings.length">
>                 
> ```

Why not just use ` ``` HTML
>   </div>
>   <div ng-if="displayWarnings.visible" class="detailsPanel">
>     <h2> Warnings in {{displayWarnings.runName}} </h2>
> ```

I think you should point out that these are duplicate [sub]test names.

---

_[index.html, line 167 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkcE5uaKebQrtcLUbJ:-KJkcE5uaKebQrtcLUbK:-545556407) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/index.html#L167)):_

> ``` HTML
>   <div ng-if="displayWarnings.visible" class="detailsPanel">
>     <h2> Warnings in {{displayWarnings.runName}} </h2>
>     <ol style="margin-left: 3em; display: list-item; text-indent: -3em;" ng-repeat="warning in displayWarnings.warnings">
> ```

Why the inline style?

---

_[index.html, line 168 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkcG4CtzXb8qgNbamj:-KJkcG4CtzXb8qgNbamk:-492495303) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/index.html#L168)):_

> ``` HTML
>     <h2> Warnings in {{displayWarnings.runName}} </h2>
>     <ol style="margin-left: 3em; display: list-item; text-indent: -3em;" ng-repeat="warning in displayWarnings.warnings">
>       <div><b>Test</b> : {{ warning.test }}</div>
> ```

Shouldn't an `ol` contain `li` elements, not `div`s?

---

_[index.html, line 170 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkcLan2UtSdCXkOOHO:-KJkcLan2UtSdCXkOOHP:809242819) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/index.html#L170)):_

> ``` HTML
>       <div><b>Test</b> : {{ warning.test }}</div>
>       <div><b>Subtest</b> : {{ warning.subtest }}</div>
>       <br />
> ```

Why the `br`?

---

_[wptview.css, line 113 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJkca90VaeGe8KYIx6m:-KJkca91CrxZ0XycRZfp:-1166387925) ([raw file](https://github.com/mozilla/wptview/blob/73bd78def1b78b6263a7d2d8141f6e5efccf369a/wptview.css#L113)):_

> ``` CSS
> }
> 
> /* Tooltip text */
> ```

I think this tooltip stuff is unneeded.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142)_

**Comment by arpan98** [comment]
Integrated your suggested changes @jgraham . I'll need some help on bringing the `detailsPanel` down. Currently it just stays up until the page is refreshed. I had a look at #95 but couldn't understand what exactly allowed the panel to close when clicked elsewhere.

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[index.html, line 165 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KJpYLEv3Gq8iNhdpx1-:-KJpYLEv3Gq8iNhdpx10:458072887) ([raw file](https://github.com/mozilla/wptview/blob/6237b6ce05f4e2456c55f580e5f60b9c4fbd5369/index.html#L165)):_

> ``` HTML
>     <h2> Duplicate tests in {{displayWarnings.runName}} </h2>
>     <ol>
>     <li style="margin-top: 0.8em;" ng-repeat="warning in displayWarnings.warnings">
> ```

Would be nice to put this style in a stylesheet

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142)_

**Comment by arpan98** [comment]
Status?

**Comment by jgraham** [comment]
There are still open issues in the review.

**Comment by arpan98** [comment]
Solved the issues with inline CSS.

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[wptview.css, line 51 [r7]](https://reviewable.io:443/reviews/mozilla/wptview/142#-KKhwfn-0Qc41WeRata6:-KKhwfn-0Qc41WeRata7:442101440) ([raw file](https://github.com/mozilla/wptview/blob/6ae96326e716f56f18375d6caf9cfed53c317f5c/wptview.css#L51)):_

> ``` CSS
> }
> 
> .detailsPanel > li {
> ```

That doesn't work since the `li` isn't a child of `<div class=detailsPanel>`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142)_

**Comment by arpan98** [comment]
Oops, trivial error. Didn't check sorry.

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/142)_

**Comment by jgraham** [comment]
Ah, dammit I clicked on the button rather than the dropdown to select "squash and merge".

Anyway, thanks for the patch!

**Comment by martiansideofthemoon** [comment]
@jgraham we shouldn't squash it in the master history right?

**Pull request merged**
