### PR TITLE
Basic progressbar added to show progress while logs are ingested.

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Follow up for #85. Attempts to solve #80

[Review on Reviewable](https://reviewable.io/reviews/mozilla/wptview/100)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 76 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxccX5nV0Ndn33VtBP:-KBxccX6rAZ9rfYwmwLN:-1605755522) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L76)):_
This can be set using a model in the scope and `ng-show`.

---

_[angular_scripts.js, line 112 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxdMHiBJFEi0-4cIxD:-KBxdMHjw640SnK4mAXM:-1188094883) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L112)):_
updateProgress could set this timeout when the tasks reaches totalTasks.

---

_[angular_scripts.js, line 170 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxcnxYEq3eOUKogJkw:-KBxcnxZk2H1Dyqp5aKw:1385539947) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L170)):_
Why is there style here?

---

_[index.html, line 11 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxdVhtPQmVt9X7VNmi:-KBxdVhtPQmVt9X7VNmj:1764580434) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/index.html#L11)):_
Make sure this is hidden by default.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 170 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxcnxYEq3eOUKogJkw:-KCfILRE47DtpWZUD5V4:-1799053835) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L170)):_
I guess this is needed to update the style dynamically in `updateProgressBarStyle`. What do you think?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 170 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxcnxYEq3eOUKogJkw:-KCh1vdnBLuDW5Irogt4:-578541694) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L170)):_
It isn't though. You can override a single style from script without defining all the styles in the script like this.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[angular_scripts.js, line 76 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/100#-KBxccX5nV0Ndn33VtBP:-KCv8lVjRiKJvuv17bks:757610526) ([raw file](https://github.com/mozilla/wptview/blob/b7b25821fc719972678a96b166924a85e2852826/angular_scripts.js#L76)):_
Move this into `updateProgress` and stop passing the `progressBar` object into this function.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/100)_

**Pull request merged**
