### PR TITLE
Follow up for cross run filters

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
This PR follows up #42

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/43)

### CODE REVIEW

**Comment by jgraham** [comment]
This wasn't really needed; you could have pulled the new commit into your branch and pushed to the original PR. Then you could have reviewed just my change…

**Comment by jgraham** [comment]
Indeed it might still be better to do it like that.

**Comment by martiansideofthemoon** [comment]
@jgraham: What would be the correct commands to do that?

**Comment by jgraham** [comment]
I don't know what you've called your remote for this repo and not your own fork, but assuming `upstream` (and if you don't have one start with `git remote add upstream git@github.com:jgraham/wptview.git`), then with your branch checked out something like:

```
git fetch upstream
git merge --ff-only pr/42
git push
```

**Comment by martiansideofthemoon** [comment]
@jgraham Well I'm getting a `fast forward not possible` on doing `git merge --ff-only upstream/pr/42`. On removing `--ff-only` I'm having to solve a merge conflict. What's going wrong?

**Comment by jgraham** [comment]
Are you on the right branch to begin with? Is 25acbf3 the topmost commit?

**Comment by martiansideofthemoon** [comment]
@jgraham , Well yeah there's the problem I guess. My top commit isn't 25acbf3 even though it has the same commit message and changes. Do local branch commits have different commit IDs?
So I guess I should reset my branch a previous commit and then try to merge?

**Comment by jgraham** [comment]
That's pretty weird… Did you rebase the local branch or something? Anyway I guess if you just reset the local branch to `pr/42` and push then we can go from there.

**Comment by martiansideofthemoon** [comment]
So I'll try a 
`git reset --hard 9555f46afbc666a962b0f9b6b0f36044260e1674` on the local version of my PR branch `my-code-fix`

**Comment by martiansideofthemoon** [comment]
Works, closing this issue and reviewing out there :smile:

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[LovefieldService.js, line 301 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/43#-K6t88yHfD2LZ8zpe6qJ:-K6t88yHfD2LZ8zpe6qK:-871825295) ([raw file](https://github.com/jgraham/wptview/blob/27d44c53cf87661f4ba42ff76636801982588e57/LovefieldService.js#L301)):_
**nit**: Missing `;`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/43)_

**Pull request closed without merging**
