### PR TITLE
Adding the error panel

### LINKED ISSUE #13: Display the error message, if any
The table has no support for displaying the error message for tests that fail. We need some UI to display messages for such tests. The UI decided is a panel fixed to the bottom that opens on clicking the status and closes on clicking anywhere else. The error message is stored here [1]. It can be accessed via `$scope.results.runs[<some_index>].message`. Something similar to `status` in [2]

[1] - https://github.com/jgraham/wptview/blob/dcc68d8ffffafc7eca8b080becd825fab5a5d61d/angular_scripts.js#L309
[2] - https://github.com/jgraham/wptview/blob/dcc68d8ffffafc7eca8b080becd825fab5a5d61d/index.html#L132

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Follow up of #82. All commits of #82 imported here thus far. Fixes #13 

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/95)

### CODE REVIEW

**Comment by CodeMaxx** [comment]
@martiansideofthemoon Did you squash commits ? There were more commits after this.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , yeah had to squash it. Resolving the conflict was impossible without doing so. Also, I've removed the indentation in index.html to make the diff readable

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[index.html, line 150 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/95#-KBSmVDfLDT5Rpt6jF_N:-KBSmVDfLDT5Rpt6jF_O:-1605728706) ([raw file](https://github.com/jgraham/wptview/blob/2b70bf34f1c825642a281b26a31d16243a3edf26/index.html#L150)):_
This panel should be zero-height when not displayed, at the moment it seems to always take up the bottom 15% of the screen.

---

_[index.html, line 152 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/95#-KBSn0sslJc55Y0lJQ4T:-KBSn0stXsuzt6WIJuU4:1286067138) ([raw file](https://github.com/jgraham/wptview/blob/2b70bf34f1c825642a281b26a31d16243a3edf26/index.html#L152)):_
Ideally the expected and got text would use the same styles as the corresponding table cells.

---

_[wptview.css, line 26 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/95#-KBSl7Qpxh1Bm81o5oRe:-KBSl7QqTdo_lXQz-jM4:-431849077) ([raw file](https://github.com/jgraham/wptview/blob/2b70bf34f1c825642a281b26a31d16243a3edf26/wptview.css#L26)):_
This doesn't seem much like it will match the other text on the page; I would try the Mono versions of the fonts defined on `:root`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/95)_

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/95)_

**Pull request merged**
