### PR TITLE
basic progressbar added

### PR DESCRIPTION
**Pull request by arpan98**
A simple progressbar added. Should the steps be shown as well?

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/85)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
tries to solve #80

**Comment by martiansideofthemoon** [comment]
I think this is great work, especially the styling. I would love @jgraham to have a look at this. A few issues, do address them. Then you can move to adding this progress bar for CLEAR and SELECT too :)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[angular_scripts.js, line 66 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/85#-K9N0vKsYDY_rKeRgzIJ:-K9N0vKsYDY_rKeRgzIK:-973923838) ([raw file](https://github.com/jgraham/wptview/blob/f070d0cc13bdef59b96924b88850a34312cfc2d8/angular_scripts.js#L66)):_
Maybe you could move this to the `ngStyle` directive instead of using `document.getElementById`. Here and elsewhere

---

_[angular_scripts.js, line 67 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/85#-K9N1259pUn-YfYQxOml:-K9N1259pUn-YfYQxOmm:-887135748) ([raw file](https://github.com/jgraham/wptview/blob/f070d0cc13bdef59b96924b88850a34312cfc2d8/angular_scripts.js#L67)):_
**nit**: space on either side of `=`. Here and elsewhere

---

_[angular_scripts.js, line 83 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/85#-K9N1OSbXnNhLTs4URM9:-K9N1OSbXnNhLTs4URMA:-1675355344) ([raw file](https://github.com/jgraham/wptview/blob/f070d0cc13bdef59b96924b88850a34312cfc2d8/angular_scripts.js#L83)):_
**nit**: probably indent this like the other promises?

---

_[angular_scripts.js, line 105 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/85#-K9N1hA-O51ORGMKOMCJ:-K9N1hA-O51ORGMKOMCK:960041431) ([raw file](https://github.com/jgraham/wptview/blob/f070d0cc13bdef59b96924b88850a34312cfc2d8/angular_scripts.js#L105)):_
I think you need to make the width zero as well here

---

_[index.html, line 12 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/85#-K9N1mf-vP8xmD1UtfKj:-K9N1mf-vP8xmD1UtfKk:1551887326) ([raw file](https://github.com/jgraham/wptview/blob/f070d0cc13bdef59b96924b88850a34312cfc2d8/index.html#L12)):_
Looks good, add the angular directives here

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/85#-:-K9N0iF3UDDfCy-xCTbo:-664794239)_

**Comment by arpan98** [comment]
@jgraham Moving to the ngStyle directive would mean that I would have to update the scope variable of bar width within the controller, however the width in previous commit being updated outside the controller as and when each promise is fulfilled. I would be glad if you could suggest a workaround for this.

**Comment by jgraham** [comment]
Some general comments:
- I would like to see this in combination with the spinner, rather than replacing it e.g. having the progress bar below the spinner.
- I wonder about using `<input type="progress">` rather than a `div`.
- The implementation could be better factored e.g. with a `setProgress(current, total)` function.
- The current implementation seems to spend a lot of time with the progress bar at 100%, which is confusing.

**Comment by arpan98** [comment]
@jgraham 
- I placed the progress bar below the spinner. I don't know why, but it looks slightly off center, or maybe it's just my eyes.
- I looked it up and tried it, but it seems that the styling is very browser-dependent with different css for each browser. A `div` seems much easier and looks better too.
- Made an `updateProgress(current, total)` function.
- Incremented the number of tasks by 1. Now the progress bar disappears as soon as it hits 100%, which looks kind of weird. Let me know what I should do with this.

**Comment by jgraham** [comment]
I seem to be getting a parse error from angular when I try to use this branch to upload a local log?

FWIW I still think that a progress element, with minimal styling, is a better approach than a custom div-based solution.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/85#-:-K9Y6cim0E_RqVUd8X-G:1943389393)_

**Comment by martiansideofthemoon** [comment]
@jgraham, parse error fixed in 8e6607f2688dd613f4636bf755f7e7711e1202a9

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[angular_scripts.js, line 53 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/85#-KA5Yg3kvmrFbfaqIJEh:-KA5Yg3kvmrFbfaqIJEi:-396002102) ([raw file](https://github.com/jgraham/wptview/blob/f85b178ab2b5f551d5659df4429ce10ab7149cf8/angular_scripts.js#L53)):_
You can make this a function in the controller and just pass the whole function in rather than passing in $scope. That seems like a better factoring because it limits the API outside the controller to just the function call rather than the whole of `$scope`.

---

_[angular_scripts.js, line 108 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/85#-KA5XtIiR-8XbEwYUO2N:-KA5XtIiR-8XbEwYUO2O:-1129515785) ([raw file](https://github.com/jgraham/wptview/blob/f85b178ab2b5f551d5659df4429ce10ab7149cf8/angular_scripts.js#L108)):_
If you don't think this should disappear immediately, you could do this in a short (100ms) timeout.

---

_[index.html, line 11 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/85#-KA5Y8I9CV-Um47nNZJD:-KA5Y8IAa6OxBkkn8141:825977425) ([raw file](https://github.com/jgraham/wptview/blob/f85b178ab2b5f551d5659df4429ce10ab7149cf8/index.html#L11)):_
I would still like to see a variant of this with a unstyled `<progress>` element.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/85)_

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/85)_

**Comment by arpan98** [comment]
@jgraham Please have a look now, I've implemented your suggestions.

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[angular_scripts.js, line 53 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/85#-KA5Yg3kvmrFbfaqIJEh:-KAGMMCVEvx0MI72P2qc:-253966188) ([raw file](https://github.com/jgraham/wptview/blob/f85b178ab2b5f551d5659df4429ce10ab7149cf8/angular_scripts.js#L53)):_
OK, the first part of this change is good, but you are still passing in `$scope` to the `ResultsModel. Please just pass in the progress updating function.

---

_[angular_scripts.js, line 146 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/85#-KAGNFUnig7-eECVn5XD:-KAGNFUoOQOwrFS4vE1I:1081280182) ([raw file](https://github.com/jgraham/wptview/blob/2c5a94d49273f1b06ac71bfde5f5b7c18cd53a29/angular_scripts.js#L146)):_
Why isn't this in the stylesheet? Or, rather, why are you repeating it here?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/85)_

**Comment by martiansideofthemoon** [comment]
@arpan98 here as well

**Comment by martiansideofthemoon** [comment]
@jgraham , so I'll take up this issue as I think it should be merged before / just after / treeherder integration

**Pull request closed without merging**
