### PR TITLE
Edit run name feature added.

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
ref #61 
imported commits from #86

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/wptview/121)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[angular_scripts.js, line 374 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/121#-KFEgdwN2aamPlceBTOb:-KFEgdwO4v8EqLJNjNac:-19882045) ([raw file](https://github.com/mozilla/wptview/blob/5cd77fdf6f298f9d6ac60e48ff5468d8306e7039/angular_scripts.js#L374)):_
The implementation here doesn't match the angular style used in the rest of the code. In particular I expect that instead of using innerHtml we will show or hide parts of the template based on the state, and use classes to define any required style rather than direct DOM manipulation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/121)_

**Comment by udiboy1209** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[edit_icon.png, line 0 [r4]](https://reviewable.io:443/reviews/mozilla/wptview/121#-KG3bC1edRusEk5UFTC5:-KG3bC1fpw05MbLGIWRC:-1651947035) ([raw file](https://github.com/mozilla/wptview/blob/eceb79889467f86a0dd45007e4356f4d40645d5e/edit_icon.png#L0)):_
This looks like a material icon. I would advise using an SVG over PNG. They render better, and kinder on the CPU too i think. An SVG will surely be available from where this PNG was downloaded

---

_[index.html, line 30 [r4]](https://reviewable.io:443/reviews/mozilla/wptview/121#-KG3anmhX_8ab_ozZNbl:-KG3anmhX_8ab_ozZNbm:-1875392296) ([raw file](https://github.com/mozilla/wptview/blob/eceb79889467f86a0dd45007e4356f4d40645d5e/index.html#L30)):_
Mouse cursor should change to a hand pointer when hovering. Else it won't look like its clickable.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/121)_

**Comment by martiansideofthemoon** [comment]
`ng-keypress` and  https://docs.angularjs.org/guide/forms#custom-validation

**Comment by arpan98** [comment]
@martiansideofthemoon Do you want to implement a custom validation form for checking if the run name already exists?
And `ng-keypress` for detecting the `Return` or `Esc` keys?

**Comment by martiansideofthemoon** [comment]
@arpan98 yes to both

**Pull request closed without merging**
