### PR TITLE
adding basic file reader

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Well this isn't a library, just wanted a review. it's a basic file reader @jgraham . In the case you want me to use JQuery, or some other major change, do let me know :smile:

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/1)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
@jgraham I've added a basic library. It reads the logs and converts to JSON successfully

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[index.html, line 6 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2kmFQwAaj11WmIzObI)** ([raw file](https://github.com/jgraham/wptview/blob/73cbf652f297067720a925243e38f956b0ab79d6/index.html#L6)):</sup>
Is this left over?



---

<sup>**[index.html, line 14 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2klWOoV0y5Bg9adgQ1)** ([raw file](https://github.com/jgraham/wptview/blob/73cbf652f297067720a925243e38f956b0ab79d6/index.html#L14)):</sup>
Let's explicitly call out that the file is utf8 encoded by providing a label argument.



---

<sup>**[index.html, line 16 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2kl2b5SKfL7PvLy5kC)** ([raw file](https://github.com/jgraham/wptview/blob/73cbf652f297067720a925243e38f956b0ab79d6/index.html#L16)):</sup>
Space after , please



---

<sup>**[logcruncher.js, line 1 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2klj3rHKBTN9PDVBu9)** ([raw file](https://github.com/jgraham/wptview/blob/73cbf652f297067720a925243e38f956b0ab79d6/logcruncher.js#L1)):</sup>
This name is arguably a bit whimsical for my taste, but you don't have to change it :)



---

<sup>**[logcruncher.js, line 2 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2kls4A4cLRe9zFHykF)** ([raw file](https://github.com/jgraham/wptview/blob/73cbf652f297067720a925243e38f956b0ab79d6/logcruncher.js#L2)):</sup>
Instead of creating an object we could just return an array for now. In the next step we may want to make reading iterative anyway.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/1)

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/1)

**Comment by martiansideofthemoon** [comment]
> Let's explicitly call out that the file is utf8 encoded by providing a label argument.

@jgraham Didn't quite get you. I've added some changes

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[index.html, line 13 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2lIEtylvOlh57_wRkK)** ([raw file](https://github.com/jgraham/wptview/blob/2e5ec0e6ce8494e8e207f6fe96acfca55e819edc/index.html#L13)):</sup>
Space after , please



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/1)

**Comment by jgraham** [comment]
Use spaces rather than tabs throughout, please.



---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[logcruncher.js, line 5 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/1#-K2lUDrOQVGBbi6JaT2C)** ([raw file](https://github.com/jgraham/wptview/blob/b76e988f2bf81ecf21c4e468eb01ba3bcf4cbf02/logcruncher.js#L5)):</sup>
Use braces here, please



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/1)

**Comment by martiansideofthemoon** [comment]
@jgraham - corrected the nits

**Pull request merged**
