### PR TITLE
Implement comments addition feature ref #62

### PR DESCRIPTION
**Pull request by udiboy1209**
Ability to add comments for each test result.

Delete part is still a bit buggy. I'll debug it later. 
Plus, insert and fetch commands are slower than expected. @martiansideofthemoon please check this.

Tries to solve #62 

[Review on Reviewable](https://reviewable.io/reviews/mozilla/wptview/99)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Copying from the IRC, not sure if you could see the message.

 I think the major issue is that you're using this.getDbConnection() again and again
 it's been stored in the object, so you don't need to do it in any of the functions
 look at how the other queries have been written
this for example [here](https://github.com/mozilla/wptview/pull/99/files#diff-91be11e7c8810436e35d269783c6e7a3R543)

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[angular_scripts.js, line 469 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBsz7wFFULcbugQwBlx:-KBsz7wFFULcbugQwBly:-2125740857) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L469)):_
add a `$scope.$apply()` here. Makes it super fast :smile: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by martiansideofthemoon** [comment]
Great job! A bit more work and we are good to merge :smile: 

---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

_[angular_scripts.js, line 130 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-TuF9hzonHeNxWFu:-KBt-TuF9hzonHeNxWFv:103403182) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L130)):_
**nit**: space between `)` and `{` here and elsewhere

---

_[angular_scripts.js, line 141 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-MPuW6Od6TmbhicA:-KBt-MPuW6Od6TmbhicB:138188254) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L141)):_
**nit**: Maybe the Lovefield function could be named as `deleteAllComments`

---

_[angular_scripts.js, line 323 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-bCZsZqfFUeWmTS1:-KBt-bCZsZqfFUeWmTS2:-1469616665) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L323)):_
Couldn't this be included in the removeResults query?

---

_[angular_scripts.js, line 476 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0ZHP3LOGRaAdv2iY:-KBt0ZHP3LOGRaAdv2iZ:2116900819) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L476)):_
Could you explain this part of the code?

---

_[angular_scripts.js, line 486 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt01YF7IH_OiT3mLdY:-KBt01YGmZR587oRmKFQ:597300915) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L486)):_
use strict equality

---

_[angular_scripts.js, line 507 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt09BzF9s8IX7rJjNU:-KBt09C-vmsFaPKjUYdI:-1365537178) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L507)):_
this is incorrect. Different runs will have different run ids. `result.result_id` should be added in the array along with `result.status`, `result.expected`, `result.message` below

---

_[LovefieldService.js, line 89 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0jVuK3mHc46adr5K:-KBt0jVvVGEQpveZr9V8:342700703) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L89)):_
**nit**: maybe `comment_id` would be better to avoid confusion with the tests table. Though upto you

---

_[LovefieldService.js, line 619 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0vAIOeVLhaSObeej:-KBt0vAJP3DE1t7fypii:-808937758) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L619)):_
I don't think this is correct join condition. The JOIN is on result id. This condition should be added to a where clause. Also, I don't think q2 should be needed
**nit**: missing `;`

---

_[LovefieldService.js, line 625 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0yqHlCEuU26ojjUq:-KBt0yqI6qa-h5eB8Dhu:-1534902185) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L625)):_
**nit**: add `{}`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99#-:-KBt1pDtiSCIXfNqWmGS:1356116857)_

**Comment by martiansideofthemoon** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[angular_scripts.js, line 130 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-TuF9hzonHeNxWFu:-KBtTif1l7MRXTyu47ak:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L130)):_
Done.

---

_[angular_scripts.js, line 141 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-MPuW6Od6TmbhicA:-KBtTkMLedDdvlRUe1E6:-395328733) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L141)):_
"All" seemed confusing because of the run_id filtering. "Multiple" maybe?

---

_[angular_scripts.js, line 323 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-bCZsZqfFUeWmTS1:-KBtU7fnwXL-SNK6wdO-:2027739436) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L323)):_
seems cleaner yea! will do it.

---

_[angular_scripts.js, line 469 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBsz7wFFULcbugQwBlx:-KBtUJroxyIfQhJYmHIm:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L469)):_
Done.

---

_[angular_scripts.js, line 476 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0ZHP3LOGRaAdv2iY:-KBtUL3XThWhdq8Z85pY:-1821243335) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L476)):_
Its for stopping periodic calls to the save function. No need for them when error panel is closed

---

_[angular_scripts.js, line 486 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt01YF7IH_OiT3mLdY:-KBtUmnTPidIq1Bd3KkN:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L486)):_
Done.

---

_[angular_scripts.js, line 507 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt09BzF9s8IX7rJjNU:-KBtVmFt5i6Zob-uCY0b:-64665719) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L507)):_
I don't see why each run would need a result_id field? From what I have understood each result has one id and multiple runs.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
I seem to have misinterpreted the database association. It seems we require one comment per result per run, so will add that to the table and queries sometime later :smile:! It was fun implementing this feature!

**Comment by jgraham** [comment]
Review status: 2 of 4 files reviewed at latest revision, 20 unresolved discussions.

---

_[angular_scripts.js, line 130 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC12goOZuOYVjNmKABb:-KC12goPofZr6kHiflqI:-996096826) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L130)):_
Space after `if`

---

_[angular_scripts.js, line 144 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC12mI7EJ5rsSv2jJig:-KC12mI7EJ5rsSv2jJih:450825151) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L144)):_
`deleteComments` should be part of the same function as `deleteEntries` rather than a separate thing.

---

_[angular_scripts.js, line 452 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13BQDRoM5lOeipmge:-KC13BQDRoM5lOeipmgf:125544053) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L452)):_
Remove this

---

_[angular_scripts.js, line 459 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13PhQHt4C5yCcZmTi:-KC13PhQHt4C5yCcZmTj:-49073774) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L459)):_
`$scope.displayError.comment = comment.length ? comment[0].comment : "";

---

_[angular_scripts.js, line 465 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC156SoXHxESp5lyaSZ:-KC156Sq4ep-K_foP_iF:-1175035527) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L465)):_
 I think a better implementation strategy might be to have a function which is called when the text box receives a `focus` event. This function will call `saveComment` and set a timeout to call the same function again. When the text box receives a `blur` event the timer will be cancelled and the `saveComment` function called directly to ensure the final state is saved.

---

_[angular_scripts.js, line 484 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18tX1-0K1L8E9TXcq:-KC18tX1-0K1L8E9TXcr:1594022689) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L484)):_
`var` here and elsewhere

---

_[angular_scripts.js, line 485 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19AKZe1bw49zMZjZW:-KC19AK_Hike49a6CEbB:743416101) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L485)):_
Prefer `camelCase` in this code

---

_[angular_scripts.js, line 487 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18y5tYqx7UykTd1QD:-KC18y5uKJr7Dw5uSIbt:-1038942650) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L487)):_
Space after `if` everywhere

---

_[angular_scripts.js, line 488 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18psG15JAlrlNlBzk:-KC18psHj_SVgKjZe2IJ:2097897961) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L488)):_
Remove

---

_[index.html, line 156 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19Kv6aq8iPif1jJ95:-KC19Kv74iNJLpypSY7v:-2071358696) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/index.html#L156)):_
Can we divide the error panel in two horizontally and put this on the right?

---

_[LovefieldService.js, line 89 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0jVuK3mHc46adr5K:-KC19VXde2x0NMBRFTZ-:1352611784) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L89)):_
(I would prefer `id` everywhere fwiw).

---

_[LovefieldService.js, line 55 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19__EeoWZFbzAmP__:-KC19__FxahxEJCPWf5F:-1047659068) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/LovefieldService.js#L55)):_
You need to increment the `1` here or Lovefield will get upset for users that already have data.

---

_[LovefieldService.js, line 582 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19woRmyf_794hQaL5:-KC19woTHRQYGnju0_iI:1762971673) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/LovefieldService.js#L582)):_
Lots more missing var here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: 2 of 4 files reviewed at latest revision, 20 unresolved discussions.

---

_[angular_scripts.js, line 323 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt-bCZsZqfFUeWmTS1:-KC1Mnd-YHgcPaU-Ob2Z:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L323)):_
Done.

---

_[angular_scripts.js, line 476 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0ZHP3LOGRaAdv2iY:-KC1Pxyr3HgCDxtVXZdH:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L476)):_
Done.

---

_[angular_scripts.js, line 507 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt09BzF9s8IX7rJjNU:-KC1RM_480rVoH7tpMpc:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/angular_scripts.js#L507)):_
Done.

---

_[angular_scripts.js, line 452 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13BQDRoM5lOeipmge:-KC1L-rTDjTutPDwxgkA:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L452)):_
Done.

---

_[angular_scripts.js, line 459 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13PhQHt4C5yCcZmTi:-KC1L2kuORHExHzZaS-z:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L459)):_
Done.

---

_[angular_scripts.js, line 484 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18tX1-0K1L8E9TXcq:-KC1PymdhVp3j8z9jVrO:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L484)):_
Done.

---

_[angular_scripts.js, line 485 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19AKZe1bw49zMZjZW:-KC1RJXNGOYylkt2842J:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L485)):_
Done.

---

_[angular_scripts.js, line 487 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18y5tYqx7UykTd1QD:-KC1RKBNokBSJZC9w4M0:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L487)):_
Done.

---

_[angular_scripts.js, line 488 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC18psG15JAlrlNlBzk:-KC1RLSa9CxviIKqYZag:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L488)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: 2 of 4 files reviewed at latest revision, 20 unresolved discussions.

---

_[LovefieldService.js, line 625 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0yqHlCEuU26ojjUq:-KC1SXIHjWnsiYHa6ujH:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L625)):_
Done.

---

_[LovefieldService.js, line 582 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19woRmyf_794hQaL5:-KC1SZR4RJEW08GIYvys:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/LovefieldService.js#L582)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: 0 of 3 files reviewed at latest revision, 20 unresolved discussions.

---

_[angular_scripts.js, line 465 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC156SoXHxESp5lyaSZ:-KC2DODqZrXvaOPORT_I:1162310566) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L465)):_
Done. sounds better than triggering on error-panel open.

---

_[index.html, line 156 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC19Kv6aq8iPif1jJ95:-KC2Ecp99TRGytBuG1bv:-1327314941) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/index.html#L156)):_
Done. Looks much better!

---

_[LovefieldService.js, line 89 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KBt0jVuK3mHc46adr5K:-KC2DHOmXW1fdPHiAcGP:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/497abad16912929f237722189ff0cb2c875552d3/LovefieldService.js#L89)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

_[angular_scripts.js, line 459 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13PhQHt4C5yCcZmTi:-KCH3dJDlL9WrG3pbSdq:1525102495) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L459)):_
It seems you forgot to remove the if/else?

---

_[angular_scripts.js, line 439 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCH76pvXPHq28DfCNoQ:-KCH76pvXPHq28DfCNoR:516942162) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/angular_scripts.js#L439)):_
Nit: can we call `run` something like `runResult`? I know this doesn't match index.html, but this is very confusing.

---

_[angular_scripts.js, line 489 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCH89Z3e7WmT9A1fLf_:-KCH89Z3e7WmT9A1fLfa:-475659398) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/angular_scripts.js#L489)):_
`!==`

---

_[index.html, line 8 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCHAjMedp6Re7SgVV6e:-KCHAjMfgOmnthVJAXBD:-1594797727) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/index.html#L8)):_
Is this still needed?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by jgraham** [comment]
Reviewed 3 of 4 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[angular_scripts.js, line 459 [r5]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KC13PhQHt4C5yCcZmTi:-KCLwSGIS0r6LQ-y6tiy:-1762708137) ([raw file](https://github.com/mozilla/wptview/blob/bfec8cfeb4c81cf4d8496f3f6cdb5d78d272fac8/angular_scripts.js#L459)):_
Oops! sorry! done.

---

_[angular_scripts.js, line 439 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCH76pvXPHq28DfCNoQ:-KCLvgypcg6uj6_CAYEV:-485999507) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/angular_scripts.js#L439)):_
I'll make the change. I guess then `result` is confusing too. rename it to something like `resultTest`?

---

_[index.html, line 8 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCHAjMedp6Re7SgVV6e:-KCLvAURZFrtXM1z0BTg:1331656545) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/index.html#L8)):_
You have a point. It isn't.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[angular_scripts.js, line 439 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCH76pvXPHq28DfCNoQ:-KCMkGbeTrNg5e8Khjk4:-485110604) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/angular_scripts.js#L439)):_
Sure.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by udiboy1209** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[angular_scripts.js, line 439 [r6]](https://reviewable.io:443/reviews/mozilla/wptview/99#-KCH76pvXPHq28DfCNoQ:-KCOouEguTaHV-fncau9:-499146009) ([raw file](https://github.com/mozilla/wptview/blob/e8c612dfde04eb87a4ee188d2ede8fc1f755d250/angular_scripts.js#L439)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/99)_

**Pull request merged**
