### PR TITLE
Add ESLint and PrettyCSS linters for JS/CSS

### PR DESCRIPTION
**Pull request by udiboy1209**
ESLint throws a lot of semicolon errors currently. Not sure there exists a rule to ignore them.

PrettyCSS doesn't currently recognise `flex` and hence shows warnings. This is the corresponding [issue](https://github.com/fidian/PrettyCSS/issues/43) on its tracker.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/wptview/120)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
This might have to wait and need a rebase, the travis integration isn't exactly working

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , after a lot of fixups (and spamming the master branch, @jgraham forbids me to make history changes to master), travis seems to work :smile: you can continue working on this after a rebase

**Comment by jgraham** [comment]
Can you fix the eslint issues? This shouldn't land until it's actually passing (and that means adding all the semicolons, not disabling the check ;)

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[.eslintrc.yaml, line 4 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEHSidPHXbPWRNqytXi:-KEHSidPHXbPWRNqytXj:1963977497) ([raw file](https://github.com/mozilla/wptview/blob/2c7c9a4ac932cba8f20916db30eff5b6a6fbee76/.eslintrc.yaml#L4)):_
Is this needed?

---

_[.eslintrc.yaml, line 6 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEHTSuKF95B5G0CLS-m:-KEHTSuLft6-SsIgoNLd:210491384) ([raw file](https://github.com/mozilla/wptview/blob/2c7c9a4ac932cba8f20916db30eff5b6a6fbee76/.eslintrc.yaml#L6)):_
I feel like this should be left as the default.

---

_[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEHSoDFwzPG4aHeSHZT:-KEHSoDFwzPG4aHeSHZU:228204410) ([raw file](https://github.com/mozilla/wptview/blob/2c7c9a4ac932cba8f20916db30eff5b6a6fbee76/.travis.yml#L12)):_
If this is showing lots of warnings, let's forget about it for now.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/120#-:-KEHSwHsgrtdNIvCPl5D:-612591068)_

**Comment by jgraham** [comment]
Reviewed 3 of 4 files at r2, 4 of 4 files at r3.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[.eslintrc, line 20 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEWGAJTJZfRyip0DUpe:-KEWGAJTJZfRyip0DUpf:-1423592785) ([raw file](https://github.com/mozilla/wptview/blob/d193b92ef05cdb09d3a66aadb38728786c4e2854/.eslintrc#L20)):_
HOw did you get this list of rules?I don't know if they are all what we want. Also the value `2` is rather meaningless, and the documentation seems to be in terms of strings like `"always"` and `"never"`. Can we use those instead?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Comment by udiboy1209** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.eslintrc, line 20 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEWGAJTJZfRyip0DUpe:-KEWO5X1i29zxz2WEPCK:-107476600) ([raw file](https://github.com/mozilla/wptview/blob/d193b92ef05cdb09d3a66aadb38728786c4e2854/.eslintrc#L20)):_
Took this list from treeherder as you told me: https://github.com/mozilla/treeherder/blob/master/.eslintrc . And modified some of the values like tab width etc. to fit our project.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Comment by udiboy1209** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.eslintrc, line 20 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEWGAJTJZfRyip0DUpe:-KEWOq1ctCvMZEvBAZp0:41391501) ([raw file](https://github.com/mozilla/wptview/blob/d193b92ef05cdb09d3a66aadb38728786c4e2854/.eslintrc#L20)):_
Plus 2 and 0 seem to work like "always" and "never". Though the documentation uses strings, a lot of the examples i found at other places used 2 and 0. So I feel it would be better to stick to that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Comment by jgraham** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[.eslintrc, line 20 [r2]](https://reviewable.io:443/reviews/mozilla/wptview/120#-KEWGAJTJZfRyip0DUpe:-KEX4yft_ciBj9eUY6Sl:802573335) ([raw file](https://github.com/mozilla/wptview/blob/d193b92ef05cdb09d3a66aadb38728786c4e2854/.eslintrc#L20)):_
Thanks, this reads a lot better now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/120)_

**Pull request merged**
