### PR TITLE
Same Run Name not allowed

### PR DESCRIPTION
**Pull request by robodhruv**
with reference to Prevent two logs from having the same run name #81

resolved.

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/84)

### CODE REVIEW

**Comment by robodhruv** [comment]
@martiansideofthemoon  resolved

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[angular_scripts.js, line 205 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Iks9EnEwuIz4Ip1pM:-K9Iks9EnEwuIz4Ip1pN:-1421551743) ([raw file](https://github.com/jgraham/wptview/blob/67156a844ebfc1a26c4cfdeb99b205288c950f29/angular_scripts.js#L205)):_
I don't think we need to read this from the DOM since we store the data in js already. In particular `$scope.runs` should be what you want.

---

_[index.html, line 51 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9IlBrZVB-ps7C3whXA:-K9IlBr_rK3yI8Xv4Xen:-628486994) ([raw file](https://github.com/jgraham/wptview/blob/67156a844ebfc1a26c4cfdeb99b205288c950f29/index.html#L51)):_
So I think a better approach would be to set the control to invalid if the run name is duplicated, and also to show some text in this case to indicate the reason for the error.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/84)_

**Comment by robodhruv** [comment]
@jgraham @martiansideofthemoon : have a look!

both concerns resolved.

**Comment by martiansideofthemoon** [comment]
good job! Some nits and some real comments. Thanks for your contribution!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 181 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9MwZPlPOphqvqhIRpL:-K9MwZPmFeb1X3mdgt_A:1838875099) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L181)):_
**nit**: redundant spaces here and elsewhere

---

_[angular_scripts.js, line 210 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Mxt4_W5NDwkyCmCxu:-K9Mxt4_W5NDwkyCmCxv:1076444969) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L210)):_
**nit**: redundant variable

---

_[angular_scripts.js, line 212 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Mxz20hNttd9bbl2Ar:-K9Mxz20hNttd9bbl2As:1915907725) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L212)):_
**nit**: space on either side of `===` and space between `)` and `{`

---

_[angular_scripts.js, line 213 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Myhz1zdFBmgsTs1my:-K9Myhz1zdFBmgsTs1mz:1709468540) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L213)):_
**nit**: Maybe it's clearer if you use `true` and `false`. Also, space on either side of `=`

---

_[angular_scripts.js, line 214 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9MyRPTwbgE-opO2to6:-K9MyRPTwbgE-opO2to7:174289705) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L214)):_
Rather than using `document.getElementById`, you can use `$scope` variables and set them in the attribute values

---

_[angular_scripts.js, line 216 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9My_eISY3qW--PVDFc:-K9My_eISY3qW--PVDFd:-484111059) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L216)):_
**nit**: Probably won't be applicable, but try to format it like

```
} else {
```

---

_[angular_scripts.js, line 217 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9MyCo_JFXYrFD9QvtQ:-K9MyCo_JFXYrFD9QvtR:-302171696) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L217)):_
Probably you don't need an `else` here. It will cause errors when I have two runs and the first run name matches with the text.

---

_[angular_scripts.js, line 222 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Mx1_wsruUa5mS29kx:-K9Mx1_wsruUa5mS29ky:-56500319) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L222)):_
**nit**: trailing spaces here and below

---

_[angular_scripts.js, line 225 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9MwzeiKhydP4Ka3l9N:-K9MwzeiKhydP4Ka3l9O:1922168581) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/angular_scripts.js#L225)):_
**nit**: Try to remove all the commented out code

---

_[index.html, line 51 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9MxdI-50JgPo8H4jIC:-K9MxdI-50JgPo8H4jID:2111763904) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/index.html#L51)):_
you could probably use `ng-blur` or something here.
**nit**: `runT` isn't a very informative id.

---

_[index.html, line 53 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9Mx9Lh_APL5fIFUByR:-K9Mx9Lh_APL5fIFUByS:-253275133) ([raw file](https://github.com/jgraham/wptview/blob/4518055e2f5580f5cebd01abedca7f505478ea50/index.html#L53)):_
Rather than make this a disabled input, how about make it a paragraph? I can't see the entire error message

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/84#-:-K9MytGAc3r6AxyJm1_5:168674133)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[index.html, line 51 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/84#-K9IlBrZVB-ps7C3whXA:-K9OqfjqXBrJgWq3wZqB:-1844469242) ([raw file](https://github.com/jgraham/wptview/blob/67156a844ebfc1a26c4cfdeb99b205288c950f29/index.html#L51)):_
Sorry, I should have linked to an example of what I had in mind. http://stackoverflow.com/questions/12581439/how-to-add-custom-validation-to-an-angularjs-form covers a very similar case and seems to be an approach we can copy.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/84)_

**Comment by martiansideofthemoon** [comment]
@PrieureDeSion any progress? Please rebase, there have been several changes

**Comment by robodhruv** [comment]
@martiansideofthemoon Travis is showing errors which don't seem to exist in the file. Can you verify?

**Comment by udiboy1209** [comment]
@PrieureDeSion check and correct all these [eslint errors](https://travis-ci.org/mozilla/wptview/builds/121892918#L295). It mentions which line number in which file so shouldn't be a problem.

**EDIT:**

It doesn't look like you've made changes to those lines. Maybe you should rebase to the latest master which has the corrections for eslint, or just ignore the travis build because it doesn't error on the lines you have changed.

**Comment by robodhruv** [comment]
The lines that Travis mentioned don't have the specified issues.

**Comment by martiansideofthemoon** [comment]
@PrieureDeSion check [https://travis-ci.org/mozilla/wptview/builds/122449138](https://travis-ci.org/mozilla/wptview/builds/122449138)

**Comment by udiboy1209** [comment]
@PrieureDeSion reset hard to the "Nits resolved" commit once and try rebasing to master. Then see if travis issues are fixed

**Comment by martiansideofthemoon** [comment]
continued in #132

**Pull request closed without merging**
