### PR TITLE
Adding Travis CI

### PR DESCRIPTION
**Pull request by sumith1896**
We need think if we need Travis or not.
Feel free to close if not needed, I had it up anyways.

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/55)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Tries to fix #56

**Comment by sumith1896** [comment]
I need to put up a habit of mentioning that :smile:

**Comment by sumith1896** [comment]
@martiansideofthemoon Any updates on this?

**Comment by martiansideofthemoon** [comment]
@Sumith1896 , ah I really forgot to ask @jgraham . I'll ask him tomorrow, though he should come around for sometime. If not, let's merge this and try it out tomorrow

**Comment by sumith1896** [comment]
Do you want to get https://github.com/jgraham/wptview/pull/51 merged first? I can get it ready to merge.

**Comment by martiansideofthemoon** [comment]
@Sumith1896 , yeah preferrably. That would be the first step in checking how well Travis works

**Comment by sumith1896** [comment]
Sounds good to me.

**Comment by jgraham** [comment]
In the short term setting up Travis to push `master` to `gh-pages` when PRs land would be great. You should be able to find some guides on how to set that up on the internet e.g. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd but note that since we aren't actually building anything there's no need to do the whole make a compile script, create a new git repo, etc. dance in the `deploy.sh` script it creates; all that's really needed is to run `git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1` on non-PR branches, with the environment set up as described in the gist.

**Comment by sumith1896** [comment]
Thanks @jgraham .Will do asap.

**Comment by sumith1896** [comment]
@martiansideofthemoon @jgraham I've been very busy especially with exams and GSoC work. I'll get back to this soon. Sorry for the delay.

**Comment by martiansideofthemoon** [comment]
@Sumith1896, it's alright, I can use your commits to complete the bug if you happen to remain busy :smile:

**Comment by martiansideofthemoon** [comment]
@Sumith1896 , I'll probably take this up. Needs to be done next

**Comment by sumith1896** [comment]
Yeah go ahead @martiansideofthemoon . Sorry for this. I've been a little too busy, won't be able to do this.

**Pull request closed without merging**
