### PR TITLE
Incorporated filter objects to a single JSON object

### PR DESCRIPTION
**Pull request by CodeMaxx**
fix for #41 
== issue not fixed yet

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/47)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[angular_scripts.js, line 107 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xPs6E12d4MIUAKKO6:-K6xPs6E12d4MIUAKKO7:1993483036) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L107)):_
you need to change the parameters here too

---

_[angular_scripts.js, line 109 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xQup14COLRbf1bc4d:-K6xQup14COLRbf1bc4e:-1781823878) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L109)):_
and here as well

---

_[angular_scripts.js, line 143 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xPIbH3lvQKrsEusa4:-K6xPIbIuCpzM2_YBIqE:-1610118641) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L143)):_
Good start, maybe we could move this to `$scope` and add the contents of the other `$scope` objects to this JSON. Also, you will need to make changes to index.html to allow this to work.

---

_[logcruncher.js, line 16 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xRE_CzwXpOJ5ibURO:-K6xRE_CzwXpOJ5ibURP:724122898) ([raw file](https://github.com/jgraham/wptview/blob/0ec20c7d6698b14d33c588dd9d436ab523f6ffad/logcruncher.js#L16)):_
**nit**: Add a space on either side of `=` and `<`

---

_[logcruncher.js, line 17 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xRHnLAzpoESaZLzob:-K6xRHnLAzpoESaZLzoc:1438693527) ([raw file](https://github.com/jgraham/wptview/blob/0ec20c7d6698b14d33c588dd9d436ab523f6ffad/logcruncher.js#L17)):_
**nit**: Add a space on either side of `===`

---

_[logcruncher.js, line 32 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xRbymZ9tWa8T3G4hA:-K6xRbymZ9tWa8T3G4hB:-1125923497) ([raw file](https://github.com/jgraham/wptview/blob/0ec20c7d6698b14d33c588dd9d436ab523f6ffad/logcruncher.js#L32)):_
**nit**: Add the space here as well. Sorry this isn't mentioned in the issue, but do it here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by CodeMaxx** [comment]
Whats the problem in line 143?

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

_[angular_scripts.js, line 127 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xToh2jFeA3LBWxLxe:-K6xToh2jFeA3LBWxLxf:225188090) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L127)):_
So we want to move this object completely inside `$scope.filter`

---

_[angular_scripts.js, line 128 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xTnjcuzBRyJEarAIU:-K6xTnjcuzBRyJEarAIV:225188090) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L128)):_
So we want to move this object completely inside `$scope.filter`

---

_[angular_scripts.js, line 140 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xThRZLK-Cx9o0wXDw:-K6xThR_UsXp2JseGhcP:225188090) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L140)):_
So we want to move this object completely inside `$scope.filter`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

_[angular_scripts.js, line 143 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xPIbH3lvQKrsEusa4:-K6xXtgkGbeYRiDsI7Uu:-1613353895) ([raw file](https://github.com/jgraham/wptview/blob/779645b6ccc505f4c2fb2f2090ef35d1763f6931/angular_scripts.js#L143)):_
so put this on `$scope` and remove the other 3 variables

---

_[index.html, line 95 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xY-oRTfOQYjmLQSyN:-K6xY-oRTfOQYjmLQSyO:-1477224418) ([raw file](https://github.com/jgraham/wptview/blob/5cbd9476edb98ca365455e065b07552df381b977/index.html#L95)):_
Change this `ng-model` as well

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

_[angular_scripts.js, line 139 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xaSF1t4yjHgw3gZWS:-K6xaSF2sy2HrU8iipOe:1149882416) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L139)):_
**nit**: Add a space after `:`

---

_[angular_scripts.js, line 141 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xaVknHGpTN1PKl0oc:-K6xaVknHGpTN1PKl0od:-1178881486) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L141)):_
**nit**: Add a space here too. Lots of indentation and trailing space errors here. Please see other JSON and then update

---

_[angular_scripts.js, line 221 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xalsmZHRfAtu41XIt:-K6xalsmZHRfAtu41XIu:1334867189) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L221)):_
Make this `$scope.filter`

---

_[angular_scripts.js, line 245 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xahjRA6aNoctJ0VEO:-K6xahjRA6aNoctJ0VEP:1334867189) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L245)):_
Make this `$scope.filter`

---

_[angular_scripts.js, line 253 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xaofa0h7mg__Ux9Ev:-K6xaofa0h7mg__Ux9Ew:1334867189) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L253)):_
Make this `$scope.filter`

---

_[angular_scripts.js, line 257 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xaqvJueBqiaaVvV4r:-K6xaqvJueBqiaaVvV4s:1334867189) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L257)):_
Make this `$scope.filter`

---

_[angular_scripts.js, line 264 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xatHcEouFgEV5mp-M:-K6xatHcEouFgEV5mp-N:911735073) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L264)):_
Make this $scope.filter

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[angular_scripts.js, line 142 [r6]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xdRUK-avg83DkgCYv:-K6xdRUK-avg83DkgCYw:1614149689) ([raw file](https://github.com/jgraham/wptview/blob/469f4061de642ec9dcca9b75f12f821c0374133b/angular_scripts.js#L142)):_
**nit**: So we use 2 space and not tab as indentation. Please fix this. Also, this line and the next have trailing spaces. Also fix the indent for the next line

---

_[angular_scripts.js, line 222 [r6]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xdaJgwwI9Wj2K1808:-K6xdaJgwwI9Wj2K1809:2130346008) ([raw file](https://github.com/jgraham/wptview/blob/469f4061de642ec9dcca9b75f12f821c0374133b/angular_scripts.js#L222)):_
**nit**: Move these parameters to the previous line. Make sure you have a space after `,`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[angular_scripts.js, line 139 [r5]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xjrcfOvLrJoNAdclW:-K6xjrcfOvLrJoNAdclX:-478695308) ([raw file](https://github.com/jgraham/wptview/blob/a95094055913928964683e96c35d711ee47d0df5/angular_scripts.js#L139)):_
We are using two spaces instead of tabs. This line has 3 spaces, please make it 4. The same for four lines below. I'm sorry we're so fussy about these indentation fixes. In the end, it has to be consistent and readable. Please bear with me. You won't make these mistakes in the future if you take this to completion.

---

_[angular_scripts.js, line 144 [r7]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xkJxIs2MWHJjECCTe:-K6xkJxJt6TfwzUsnkjT:507689253) ([raw file](https://github.com/jgraham/wptview/blob/97863c5fd09ff5074edea55a94b043310c2c2a6a/angular_scripts.js#L144)):_
trailing space here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[LovefieldService.js, line 289 [r7]](https://reviewable.io:443/reviews/jgraham/wptview/47#-K6xmSbkjzDsu9aGkkrX:-K6xmSblVcGQ0XI_w1kH:-1846917237) ([raw file](https://github.com/jgraham/wptview/blob/97863c5fd09ff5074edea55a94b043310c2c2a6a/LovefieldService.js#L289)):_
**nit**: Ah small thing here too, sorry. Put this in the previous line, space after `,`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by CodeMaxx** [comment]
@martiansideofthemoon  Thanxx for the review. :D I'll take care of the indentation next time on.

**Comment by martiansideofthemoon** [comment]
Reviewed 1 of 3 files at r4, 1 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/47)_

**Comment by martiansideofthemoon** [comment]
Looks good to me. **r+**.
@jgraham , Anything else is needed?
@CodeMaxx thanks for your contribution. :smile: Please rebase (we've merged the license PR) and squash. Hoping to see your contributions in the future.

**Pull request merged**
