### PR TITLE
Added test_code_quality.py as a lint for wptview

### PR DESCRIPTION
**Pull request by sumith1896**
We were recently working on something similar over at [SymEngine](https://github.com/symengine/symengine)
Also more checks can easily be added on top of this.
cc @martiansideofthemoon

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/51)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
@Sumith1896,
Thanks for this lint file. There are a few things I'd like you to do before I actually review it. So we would ideally want the lint to run as an executable in the base folder as `./lint` or integrated with `git commit`. That would be ideal and I'll be really grateful if you could make the needful changes.

Secondly, if you could document the exact functionality of this lint file it would be excellent. Something like what sort of nits it picks up. This could be added as in the code as comments or in a separate file. As these lints were originally designed for C++ code, I need to be sure that they will work in JS / CSS as well. So telling me the exact functionality will clear some queries in my mind.

Lastly, the included / excluded files are likely to change. So if you could move the list of included / excluded files and folders to an external folder.

(This pull request tries to fix #22)

**Comment by sumith1896** [comment]
@martiansideofthemoon I'll get back to you soon

**Comment by jgraham** [comment]
I wonder if a more promising approach would be to add support for running eslint with an appropriate rule set?

**Comment by martiansideofthemoon** [comment]
@Sumith1896 any progress?

**Comment by sumith1896** [comment]
As discussed with @martiansideofthemoon, `eslint` will be preferred over the python script.

**Pull request closed without merging**
