### PR TITLE
Prevent upload with duplicate run_name

### PR DESCRIPTION
**Pull request by nihal111**
This checks through all runs to prevent upload of a log with an existing run name. In reference to issue #81. @martiansideofthemoon Have a look.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/wptview/132)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 326 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZMTCdZJfJXXxkWsN:-KHsZMTDP4EvtbNDM6sC:-733639444) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L326)):_

> ``` JavaScript
> 
>   $scope.fetchLog = function () {
>     if ($scope.upload.logSrc === 'file') {
> ```

Why is this inside this condition? Won't it apply for URLs too? Perhaps you could disable the `Import` Button itself?

---

_[angular_scripts.js, line 328 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZ0R9T4q5GTF0nQe8:-KHsZ0RAkBmVCetJz39j:-1125795640) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L328)):_

> ``` JavaScript
>     if ($scope.upload.logSrc === 'file') {
>       var run_names = [];
>       $scope.runs.forEach((run) => {
> ```

use `map` instead

---

_[angular_scripts.js, line 332 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZUY5dulzF-KfYa_5:-KHsZUY5dulzF-KfYa_6:-1770855274) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L332)):_

> ``` JavaScript
>       });
>       //Check if run having same run_name exists
>       if ( run_names.indexOf($scope.upload.runName) !== -1 ) {
> ```

Remove spaces between `(` and condition

---

_[angular_scripts.js, line 333 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZYiG5F8L-pEOIn64:-KHsZYiG5F8L-pEOIn65:1988737656) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L333)):_

> ``` JavaScript
>       //Check if run having same run_name exists
>       if ( run_names.indexOf($scope.upload.runName) !== -1 ) {
>         console.log("A run with name ",$scope.upload.runName," already exists.");
> ```

Use `+` for concatenation

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132)_

**Comment by martiansideofthemoon** [comment]
Good start, try using `ng-keyup`

<details><summary>

<i>Previously, nihal111 wrote…</i></summary>



> #### Prevent upload with duplicate run_name
> 
> This checks through all runs to prevent upload of a log with an existing run name. In reference to issue #81. @martiansideofthemoon Have a look.
> 
> </details>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132#-:-KHs_RA49aNDAdB1k3VW:-1259007981)_

**Comment by nihal111** [comment]
How would I use ng-keyup? Should I create and update the run_names array everytime a log is imported? And why to use a map? Isn't an array appropriate here?

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> Good start, try using `ng-keyup`</details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132#-:-KHsfKq7A6EgUiZlCS0r:1510384877)_

**Comment by martiansideofthemoon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 328 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZ0R9T4q5GTF0nQe8:-KHvT13TJZI421hxBoNL:1532438145) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L328)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> use `map` instead</details>
> No, write it as 
> `var run_names = $scope.runs.map((run) => run.name);`

---

_[angular_scripts.js, line 333 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHsZYiG5F8L-pEOIn64:-KHvTOHF9sTwOeO34r50:1445768970) ([raw file](https://github.com/mozilla/wptview/blob/b94f3787b74bb2fb2c8bb64567117f9d11483891/angular_scripts.js#L333)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> Use `+` for concatenation</details>
> **nit**: Space on either side of binary operator `+`

---

_[index.html, line 56 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHvTknLk0fjkeMo9ZVK:-KHvTknLk0fjkeMo9ZVL:1627182241) ([raw file](https://github.com/mozilla/wptview/blob/c7b0b8ab5762c864c66f41f94de1a86a02b02906/index.html#L56)):_

> ``` HTML
>               <br><br>
>             <input name="run" type="text" ng-model="upload.runName" required ng-disabled="busy" placeholder="Run name">
>             <button ng-click="fetchLog()" ng-disabled="busy || (upload.logSrc == 'file' && isFileEmpty) || (upload.logSrc == 'url' && !upload.logUrl) || !upload.runName  || (!fileEvent.target.value && upload.logSrc == 'file') || duplicate_run_name()" for="fileInput" >Import Log</button>
> ```

There is a mistake here. Try typing a valid run name and no file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132)_

**Comment by martiansideofthemoon** [comment]
@nihal111 good job, a bit more needed :smile:

**Comment by robodhruv** [comment]
I forgot #84 existed. All the best @nihal111

**Comment by nihal111** [comment]
@martiansideofthemoon Made the said changes. Have a look!

**Comment by martiansideofthemoon** [comment]
You forgot to correct one mistake, almost there :smile: 

<details><summary>

<i>Previously, nihal111 (Nihal Singh) wrote…</i></summary>



> @martiansideofthemoon Made the said changes. Have a look!</details>

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[index.html, line 56 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHvTknLk0fjkeMo9ZVK:-KHz2VyewSyuwS6c4OJ6:-217365055) ([raw file](https://github.com/mozilla/wptview/blob/c7b0b8ab5762c864c66f41f94de1a86a02b02906/index.html#L56)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> There is a mistake here. Try typing a valid run name and no file</details>
> This is still incorrect. For the case when there is no file and you add a valid name, I should not be allowed to press import.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132#-:-KHz2jwV87qtegVG9cVj:-315966578)_

**Comment by nihal111** [comment]
_[index.html, line 56 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHvTknLk0fjkeMo9ZVK:-KHz9BlOD4ttIQ1Anhzr:2010418927) ([raw file](https://github.com/mozilla/wptview/blob/c7b0b8ab5762c864c66f41f94de1a86a02b02906/index.html#L56)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> This is still incorrect. For the case when there is no file and you add a valid name, I should not be allowed to press import.</details>
> Yes it was incorrect for a long time. The case when neither file nor url is selected had not been dealt with. It looks good now

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132)_

**Comment by nihal111** [comment]
_[index.html, line 56 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/132#-KHvTknLk0fjkeMo9ZVK:-KHz9BlOD4ttIQ1Anhzr:2010418927) ([raw file](https://github.com/mozilla/wptview/blob/c7b0b8ab5762c864c66f41f94de1a86a02b02906/index.html#L56)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> This is still incorrect. For the case when there is no file and you add a valid name, I should not be allowed to press import.</details>
> Yes it was incorrect for a long time. The case when neither file nor url is selected had not been dealt with. It looks good now

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132)_

**Comment by nihal111** [comment]
I think the issue is fixed now @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/wptview/132)_

**Pull request merged**
