### PR TITLE
Move log processing and database operations to a worker thread.

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/39)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

_[angular_scripts.js, line 108 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69bixZX7q1Hfm_5G2f:-K69bixZX7q1Hfm_5G2g:-462728388) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L108)):_
**nit**: Could we break a line here? Consistency with the rest of the project. At the end of the array as well

---

_[angular_scripts.js, line 186 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69eQFmqPJywnYfJAfv:-K69eQFnh2vIUepbnN_Q:-195771680) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L186)):_
**nit**: A comment might help here telling us how the the SELECT query uses the variables `minTestId`, `maxTestId` and `limit` are used. Not a compulsory issue, it's just that I couldn't understand this code without reading LovefieldService.js especially due to the importance of the `null` value in those variables

---

_[angular_scripts.js, line 190 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69hDxfMZ5jz3VtHy7N:-K69hDxfMZ5jz3VtHy7O:-1272148797) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L190)):_
Could we define `resultsView.firstTestId` as `null` in the first initialization as well?

---

_[angular_scripts.js, line 192 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69inpcukLOY6LPn7tP:-K69inpcukLOY6LPn7tQ:38753049) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L192)):_
This won't be a sufficient condition right? Haven't really worked it out, but what if the total number of results are a multiple of the `limit` or something on those lines?

---

_[index.html, line 107 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69asymlBiKYUAK_ERZ:-K69asymlBiKYUAK_ER_:1539604388) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/index.html#L107)):_
A small complaint here. I observed that the UI is responsive while the `SELECT` query is running. Shouldn't we have a `$scope.busy = true` in the `fillTable()` function?

---

_[LovefieldService.js, line 360 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69fUSk7f8VfdWOMIZB:-K69fUSl37WKGMRp7wFw:-1799021561) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/LovefieldService.js#L360)):_
**nit**: Missing `;` here and below

---

_[LovefieldService.js, line 363 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69ke1ecIN_fNkanoC_:-K69ke1ecIN_fNkanoCa:389008090) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/LovefieldService.js#L363)):_
No issues with the functionality, but an issue with the clarity. Could you add a comment here? Took me sometime to get this, as I was constantly thinking that the final results would be in `DESC` as well

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by jgraham** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

_[angular_scripts.js, line 192 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69inpcukLOY6LPn7tP:-K69womnBT5spHTl-iCe:-493159256) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L192)):_
Right, but we can't know that without doing a limit + 1 query and displaying only limit rows, which I suppose is possible but seems quite complicated.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 15 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AGf9OfITGhIU9e1zW:-K6AGf9PnbrRW1jd2z42:-871825295) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L15)):_
**nit**: Missing `;`

---

_[angular_scripts.js, line 27 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AfSligDWor03VzrMI:-K6AfSligDWor03VzrMJ:716036365) ([raw file](https://github.com/jgraham/wptview/blob/02755cf918c0ab30c372cc1271ec4cea0b59c5f2/angular_scripts.js#L27)):_
What is the reason for moving this to the `LovefieldService`?

---

_[angular_scripts.js, line 35 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AblfDFEkYm1mANvVs:-K6AblfDFEkYm1mANvVt:-877588410) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L35)):_
Well more of a doubt rather than a fix. How does this `Promise` resolve when the `Promise` inside the Worker API finishes (I mean the `services.apply()` `Promise`) ?
 From what I've understood, you are using the `resolve` object cleverly by storing it as a `WorkerService` data member and executing it (`resolve(data)`) when `service.apply()` posts a message to `WorkerService` after completion.

---

_[angular_scripts.js, line 79 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6Af-fZH-bbZ0bK8yFK:-K6Af-fZH-bbZ0bK8yFL:1846071387) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L79)):_
**nit**: Trailing `;`

---

_[logcruncher.js, line 12 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6Aed3PsBIvg4B-GiSi:-K6Aed3Qws3Q1jLStfGa:-1045378501) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/logcruncher.js#L12)):_
Can we make this a part of the `LogReader` prototype?

---

_[LovefieldService.js, line 496 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6A_pb7ZmBzvmaQ-y9V:-K6A_pb8qdTq_4hTNUyb:156248650) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/LovefieldService.js#L496)):_
Could we move this to the beginning of the file? Like in logcruncher.js

---

_[workerApi.js, line 7 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AdjA-Qyu0Uy2070TE:-K6AdjA0IshIEj8nebb6:-539702949) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/workerApi.js#L7)):_
**nit**: Maybe we could improve the logs by saying `<Service> got command ...`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by martiansideofthemoon** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by martiansideofthemoon** [comment]
This PR attempts to fix #18 
It also tries to do the finishing touches for #25 and #26

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 35 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AblfDFEkYm1mANvVs:-K6AljIERJcJb4tlvT4p:-283470248) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L35)):_
Right, So what is going on is that we have a bridge between the event-based API for communicating with workers, and the promise based API we previously implemented both on both the main thread and now inside the workers. 

In this part of the code we first post a message to the worker telling it to do something and then create a promise that will be resolved later when we get result back from a worker. In the `workerApi.js` file we receive the message posted here. Then we use the content of that message to select the function to run; that function returns a promise, which we add a `then` to which posts a message back to the main thread with the results of this function. The final part of the puzzle is the `this.worker.onmessage` function above, which receives the reply from the worker, looks up the correct resolver and calls it with the data returned from the worker thread so that the promise we originally created is then resolved with this value. From the point of view of the code on both sides this just creates a normal promise-based API; they don't know that there's async event stuff happening in the middle (indeed that kind of abstraction is rather the point of promises).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by martiansideofthemoon** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 35 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AblfDFEkYm1mANvVs:-K6CazhroX3mxULh-y5P:-1079840442) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L35)):_
Oh alright makes sense now. Just one more fundamental question, How can you say the actual process is off the main thread? Is it because it is executed inside a `postMessage()` which is a part of `Worker` and hence off the main thread?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 35 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AblfDFEkYm1mANvVs:-K6Cxmwg_avpG5FEpIBQ:804037605) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L35)):_
Not directly; one can `postMessage` on a single thread (or between different windows, for example). The fact that we run the code in a worker is determined by the fact that we call `new Worker(worker_script)` above, for both `LovefieldService.js` and `logcruncher.js`, rather than including them via a HTML script element. After that `postMessage` is the only available method of communication.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[angular_scripts.js, line 27 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6AfSligDWor03VzrMI:-K6U8GFV9EMrnIsClmac:-1888890817) ([raw file](https://github.com/jgraham/wptview/blob/02755cf918c0ab30c372cc1271ec4cea0b59c5f2/angular_scripts.js#L27)):_
You can't return a db connection object from a worker, and it creates a simpler API if all the LovefieldService methods implicitly create the database connection if it isn't already established.

---

_[angular_scripts.js, line 186 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K69eQFmqPJywnYfJAfv:-K6UGMgNaef6RwAGS6Ul:-1158610414) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/angular_scripts.js#L186)):_
I've added some JSDoc to the `getResults` method.

---

_[logcruncher.js, line 12 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/39#-K6Aed3PsBIvg4B-GiSi:-K6UGub8k8TStKhY4UJf:-1357759624) ([raw file](https://github.com/jgraham/wptview/blob/42983c3d3f9dcdac50048db927af393d719708c0/logcruncher.js#L12)):_
Well we could, but this way the internals are private to the worker and can't be accessed directly via the postMessage API.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/39)_

**Comment by martiansideofthemoon** [comment]
**r+** if the code is working. Can't test it right now :(

**Pull request merged**
