### PR TITLE
Adding test_results table to IndexedDB

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@jgraham It works alright as far as I know. I can see the two tables and appropriate data entered into it. However, I'm getting some strange values though on looking at the resources tab of my Developer Tools. I see entries of the following kind :- 

> { id : (some odd number) , value : { (the actual columns in the table, along with autoincrement id) } }

Is this just the way IndexedDB functions or am I messing up something?

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/4)

### CODE REVIEW

**Comment by jgraham** [comment]
I think that's just the way IndexedDB functions. The fundamental underlying data structure is key: value, where value is a thing that's cloneable. I don't know exactly what this adds on top of that.

**Comment by martiansideofthemoon** [comment]
@jgraham  Alright! I hope the PR is fine

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[LovefieldService.js, line 47 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FeCyxFOa1N4dW23Nm)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L47)):</sup>
Space after ,



---

<sup>**[LovefieldService.js, line 54 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FeEv5kikTTkHbf-jM)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L54)):</sup>
Space after ,



---

<sup>**[LovefieldService.js, line 72 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FT28VzsgjxdnZPEus)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L72)):</sup>
It isn't a safe assumption that each test_start/test_end pair happens in order like this. In particular the format is designed to support (and actually used in a mode where) multiple tests run at the same time, so you can get many test_start messages before a single test_end message.

If you want to do a single insert at the end, you'll need to store an map of some sort holding the tests that are currently in progress.



---

<sup>**[LovefieldService.js, line 76 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FTQ1kfru3P7y1g8-z)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L76)):</sup>
I don't think this should be _file



---

<sup>**[LovefieldService.js, line 81 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FehMMubd4kD11BYkA)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L81)):</sup>
Let's put this on the previous line.



---

<sup>**[LovefieldService.js, line 85 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FTZ2iWFWI1tmp-L0_)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L85)):</sup>
I don't think you want to store this here, because it duplicates the information in the tests table.



---

<sup>**[LovefieldService.js, line 98 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FezMMecdZRwy5IwBZ)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L98)):</sup>
So I think you want to get the test_id here when you insert the row rather than trying to work out what it will be earlier on. I'm not 100% sure what the best way to do that is with this library; you may need to insert and select and insert, or there might be an easier way.



---

<sup>**[LovefieldService.js, line 99 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3FTWhIDCSNgtD2GUR7)** ([raw file](https://github.com/jgraham/wptview/blob/8ad1728768e1f8f384729f63e40ec42b82b8b8f3/LovefieldService.js#L99)):</sup>
Trailing whitespace



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/4)

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[index.html, line 18 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3X7XBo3JlRwV5d7hYk:-K3X7XBo3JlRwV5d7hYl:-1454909480) ([raw file](https://github.com/jgraham/wptview/blob/d6a4928e17534883b4f120b10e0c716970c88ac8/index.html#L18)):_
I think the main structural problem here is that we iterate twice over the list of results. That could be avoided, and I think we should, by interleaving writes to the tests and results. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/4)_

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[LovefieldService.js, line 100 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/4#-K3oXt2BWyi98WgU7TuJ:-K3oXt2BWyi98WgU7TuK:-1254791236) ([raw file](https://github.com/jgraham/wptview/blob/b6cb6445f0c8053ec5367e08f9bc75c6709211b6/LovefieldService.js#L100)):_
Trailing whitespace

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/4)_

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/4)_

**Pull request merged**
