### PR TITLE
Added query string support as a part of Treeherder integration

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
first part of #78

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/87)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 164 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9byqtPircslMy6VM_X:-K9byqtQ9AIwkfrxQ_0c:-1847068521) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L164)):_
`.map`

---

_[angular_scripts.js, line 168 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9by7Pe21B7k9rEV7JK:-K9by7PfoxVjwE4ab1rP:975867953) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L168)):_
What happens if name is a duplicate?

---

_[angular_scripts.js, line 175 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9bxtzFOM59JcoYAYmo:-K9bxtzGu28vOqfnvWic:-45001541) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L175)):_
Consider factoring these two lines out into a function, since they are now repeated in three places.

---

_[angular_scripts.js, line 184 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9byGgcYsMXCDki_aaN:-K9byGgdwAQdWCVOjFWx:2086634539) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L184)):_
Why did this suddenly become nested?

Also two calls to updateRuns here seems rather silly; why not call updateRuns after the run is inserted?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 184 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9byGgcYsMXCDki_aaN:-K9gEi7cq5X2gOQgkhv-:-1863434827) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L184)):_
I think two updateRuns is needed now to check duplicates

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 184 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9byGgcYsMXCDki_aaN:-K9gIDj-h85ca2Kk0rzP:-94859951) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L184)):_
But why not put the second call in the `addRun` function since it's always called after a run is added?

---

_[angular_scripts.js, line 172 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9gHlyuvL7FJ5_xrqAn:-K9gHlyuvL7FJ5_xrqAo:1069965647) ([raw file](https://github.com/jgraham/wptview/blob/0895f2dde2dacf4bb89f58299eddfd3c1399410a/angular_scripts.js#L172)):_
I think this is the wrong solution. We might not want to reload a run if it was already loaded from the same url, but there's no reason to believe that run names we are loading won't clash with run names that have previously been loaded.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[angular_scripts.js, line 178 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/87#-KA5T4P_3DkaTEmMrgTv:-KA5T4P_3DkaTEmMrgTw:46524447) ([raw file](https://github.com/jgraham/wptview/blob/3c957044b76e0ff716fc77d2ec8a9d80a5d9406e/angular_scripts.js#L178)):_
I might put this +1 below the update so that the first duplicate number is (1) not (2)

---

_[angular_scripts.js, line 189 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/87#-KA5TCrLDhcFPRsPKcPI:-KA5TCrLDhcFPRsPKcPJ:2097897961) ([raw file](https://github.com/jgraham/wptview/blob/3c957044b76e0ff716fc77d2ec8a9d80a5d9406e/angular_scripts.js#L189)):_
Remove

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_[angular_scripts.js, line 164 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/87#-K9byqtPircslMy6VM_X:-KAGLq2V3nzaVuJLe0Hi:1591889950) ([raw file](https://github.com/jgraham/wptview/blob/0ae2345bc46c76937cd19a4860ee9d920d76e97b/angular_scripts.js#L164)):_
So you still didn't fix this. I guess I will merge, but if you want to make a fixup, please do.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/87)_

**Pull request merged**
