### PR TITLE
Edit run name

### PR DESCRIPTION
**Pull request by arpan98**
Edit run name after import feature added. Using Return key to confirm and Escape key to exit edit mode. #61

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/86)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
I tested it, It's really good work. The code needs some clean up though. I think you will need to remove the first commit though. I'll review once you've done that :smile:

**Comment by martiansideofthemoon** [comment]
@arpan98 , try to fix your commit message

**Comment by arpan98** [comment]
Fixed the commit message @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
@arpan98, it works great :smile: Good job, but a few mistakes and nits that must be rectified. Thanks for all the work!

---

Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

_[angular_scripts.js, line 225 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9Ko7hOwRlrhXo8AVx:-KA9Ko7hOwRlrhXo8AVy:-18876442) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L225)):_
rather than this, maybe you could use `ngModel`?

---

_[angular_scripts.js, line 226 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9KvbY9mQc2veKKpVb:-KA9KvbY9mQc2veKKpVc:1307574685) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L226)):_
**nit**: space on either side of +

---

_[angular_scripts.js, line 227 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9L9vCKIOUiPZgGQ5J:-KA9L9vCKIOUiPZgGQ5K:1185437993) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L227)):_
We have stored this in the `$scope.runs` model

---

_[angular_scripts.js, line 229 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9LHY_sovKVVIpjEq6:-KA9LHY_sovKVVIpjEq7:-430547990) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L229)):_
maybe this element could be hidden when `$scope.editSelected` is false?

---

_[angular_scripts.js, line 230 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9KippcCj08hwDSc6A:-KA9Kipqs8Kcj1S4YifQ:1455466035) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L230)):_
How about https://docs.angularjs.org/api/ng/directive/ngKeypress ?

---

_[angular_scripts.js, line 233 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9LVnnyAdKzyJ_JIPY:-KA9LVnnyAdKzyJ_JIPZ:-1918893171) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L233)):_
Not sure about the best way to do this, though I'd suggest the directive mentioned above. Maybe you could apply in on the text field and the entire `div` as well? What do you think @jgraham ?

---

_[angular_scripts.js, line 236 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9LzgJVJBFFGIv3t47:-KA9LzgKfLbjdzGEh1Mw:-1000958237) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L236)):_
This is stored in `$scope.runs`

---

_[angular_scripts.js, line 239 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9M30ctWGTTI3Eaarl:-KA9M30ctWGTTI3Eaarm:962007067) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L239)):_
use `.map`. Something like 
`names = runs.map((run) => run.name);`
It compresses the for loop into a single line :smile: 

---

_[angular_scripts.js, line 244 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9McGWW5oQuKoJNJnn:-KA9McGX8XFjCRGzUj6c:-1230524182) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L244)):_
It's a single promise here, so maybe you could write it with indentation. Also, promises are executed async, so you must add `$scope.editSelected` inside the callback of this promise, not below. Similar for the `innerHTML` changes

---

_[angular_scripts.js, line 249 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9N2-jISwm7NxI5Bik:-KA9N2-jISwm7NxI5Bil:778013554) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/angular_scripts.js#L249)):_
**nit**: Style it as `} else {`. Here and elsewhere

---

_[index.html, line 26 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9K-YKQH_soCVEjsRH:-KA9K-YLFEZUrzcXAv7b:-1395067930) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/index.html#L26)):_
could we have some visual changes to show that it is / isn't enabled? Something like a square around the button when it is enabled, or a greyed out button

---

_[LovefieldService.js, line 114 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9KDmgN53xR8ij3ELp:-KA9KDmhIP9sriiIDifC:920149671) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/LovefieldService.js#L114)):_
you don't need an `lf.op.and()` here as there is only one condition.
**nit**: you could directly return the `query.exec()` instead of creating `q1`

---

_[workerApi.js, line 13 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/86#-KA9KRr_lwDNEZF4lUnF:-KA9KRr_lwDNEZF4lUnG:555136007) ([raw file](https://github.com/jgraham/wptview/blob/2f57342e9514c3c81b022e29ca98aae226e22e9e/workerApi.js#L13)):_
**nit**: this shouldn't be there

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/86#-:-KA9NDczflZRqYDqLXCx:-2094379062)_

**Comment by martiansideofthemoon** [comment]
@arpan98 rebase here too

**Comment by martiansideofthemoon** [comment]
I'll work on this @arpan98

**Pull request closed without merging**
