### PR TITLE
Implement Log ingestion by URL

### PR DESCRIPTION
**Pull request by udiboy1209**
ref #48

Uses XMLHttpRequest, could not figure out how to get a $http instance in logcruncher.
Follows structure similar to readFile routine in terms of generating a chain of Promises.

**Haven't tested**. I get `Access-Control-Allow-Origin` error every time. 
PS was testing with this [url](http://mozilla-releng-blobs.s3.amazonaws.com/blobs/mozilla-inbound/sha512/05a68f7a1acdd9f9c800e587f576083678588c9271d9221878f3cf959063473bc6783ca09c75eacd39990ac037b0b9ec3c806a8e910c74388609fff1be8fe570)

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/68)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Great job! I was able to successfully load some mozlog from a URL after a few changes. It's really surprising that you get the "Access... " error. Are you hosting the website on a SimpleHTTPServer? Which browser are you testing it on

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[angular_scripts.js, line 59 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80iGbwAGJbV2NmX5tA:-K80iGbwAGJbV2NmX5tB:-468218791) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/angular_scripts.js#L59)):_
So one way to use `$http` is to use it here and execute the promise only when `fetchFunc` is readURL. Though this might get a little complicated. I'm perfectly happy with the current technique, though @jgraham will also have an opinion on this. He should be back in a couple of days.

---

_[logcruncher.js, line 12 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jse18sDKsyWzG3PI:-K80jse18sDKsyWzG3PJ:1524129186) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L12)):_
I don't think `httpService` is required here

---

_[logcruncher.js, line 14 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jVhSzRcjjs0TtMP9:-K80jVhTZ1cNVrLwldtx:-1208337465) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L14)):_
This needs to be changed to `log` and not `log.data`

---

_[logcruncher.js, line 50 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jzvviR1cKs4Vpi_3:-K80jzvviR1cKs4Vpi_4:1741997301) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L50)):_
**nit**: Space on either side of `=`

---

_[logcruncher.js, line 55 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80k31lnhS_eLYLpuqt:-K80k31lnhS_eLYLpuqu:1147128444) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L55)):_
**nit**: Space after `,`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68#-:-K80h8r8R6wmX-uUrzKZ:1321948812)_

**Comment by martiansideofthemoon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by udiboy1209** [comment]
I did use SimpleHttpServer but I might have used another log. I have given the link of what I used in the description above. Give me a link of some log you used, and I'll try it with that

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[logcruncher.js, line 12 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jse18sDKsyWzG3PI:-K810dywyrGhmZHwGRyr:-1894108541) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L12)):_
was trying to get a $http instance into logcruncher using this, but it failed. I'll remove it, it's useless.

---

_[logcruncher.js, line 14 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jVhSzRcjjs0TtMP9:-K810No4rTjscb_5Qra8:369126584) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L14)):_
Couldn't test this so I don't know. Might be a bug. I don't mind changing it if you have tested this.

---

_[logcruncher.js, line 50 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80jzvviR1cKs4Vpi_3:-K811EqrMRAforbaDi-A:-556005284) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L50)):_
*_Tries looking for a pep8 equivalent for js :stuck_out_tongue: *\_

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68#-:-K812B-3qpZSejoUrF9-:-840003430)_

**Comment by martiansideofthemoon** [comment]
Well the same link works for me o.O Which browser are you working on?
Also, **r+** from me.  Maybe a little work on the style? It could be done in another PR anyway.
Let's see whether it works for @jgraham before the merge.
Thanks for the work! :smile: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68#-:-K83Gy0IShpVBZ5sCvih:-83806062)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

_[index.html, line 50 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8Kb7mE1obpqjFJTIMC:-K8Kb7mE1obpqjFJTIMD:619587635) ([raw file](https://github.com/jgraham/wptview/blob/c6f9a1725e8ffb5061338311b66f158546a69b08/index.html#L50)):_
FWIW I would prefer a single form with either a URL option or a file upload option. This means you sometimes need to check if there's a file or a URL and if so, which, and then do the right thing.

---

_[index.html, line 51 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8KatOnDPfUEHwzhDLA:-K8KatOpCV5R9BiUg1UL:1062537784) ([raw file](https://github.com/jgraham/wptview/blob/c6f9a1725e8ffb5061338311b66f158546a69b08/index.html#L51)):_
Let's just use `<input type=url>` here rather than having some complex regexp

---

_[logcruncher.js, line 53 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8KbQcAScOh1lyzOaM3:-K8KbQcAScOh1lyzOaM4:708805906) ([raw file](https://github.com/jgraham/wptview/blob/c6f9a1725e8ffb5061338311b66f158546a69b08/logcruncher.js#L53)):_
It feels like in other `readyState = 4` cases you should reject the promise. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by jgraham** [comment]
This works fine for me, but the UI needs a bit of work before I'm happy with landing it.

**Comment by udiboy1209** [comment]
@jgraham I merged the two forms into one. Now another function `fetchLog()` checks what is provided and calls the appropriate function. Also added the case when `readyState == 4 and status != 200`, it rejects the Promise.

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[angular_scripts.js, line 181 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8UNFDYj7XVs1N8ZPpw:-K8UNFDZ2-0A6rTzMuZe:-1947037519) ([raw file](https://github.com/jgraham/wptview/blob/6e7a1d97ef6339e6676d15981fbbb5f4c93809ac/angular_scripts.js#L181)):_
Space after `if` and before `{` (also wherever else this is wrong).

---

_[index.html, line 51 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8USogZdgIz_LKcNbs_:-K8USog_cOvHslP_qVl8:-1906187245) ([raw file](https://github.com/jgraham/wptview/blob/6e7a1d97ef6339e6676d15981fbbb5f4c93809ac/index.html#L51)):_
I'm surprised this works. Surely it should be disabled if 
``busy || (!fileInput.log_url.$valid && (isFileEmpty || fileInput.$invalid))`

---

_[logcruncher.js, line 52 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8UTD8lUiv8V773d8yc:-K8UTD8mQEPFw0WpGBA0:-996096826) ([raw file](https://github.com/jgraham/wptview/blob/6e7a1d97ef6339e6676d15981fbbb5f4c93809ac/logcruncher.js#L52)):_
Space after `if`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by udiboy1209** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[index.html, line 51 [r3]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8USogZdgIz_LKcNbs_:-K8Vfh0okQQoJykz53Ko:2021846371) ([raw file](https://github.com/jgraham/wptview/blob/e68c261496c6ed5fac1346093c3b5ec340a6fff8/index.html#L51)):_
Looks logically correct, but when I changed it to this, it didn't work. the button is enabled initially and disabled when I input everything correctly :confused: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by udiboy1209** [comment]
@jgraham please review. I added a radio option.

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[index.html, line 49 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8tIIV3qOY3AmV3k8E1:-K8tIIV4WxRcpRUYyioJ:-2043738659) ([raw file](https://github.com/jgraham/wptview/blob/e53190c9796468fc3dc3a04800fe8ff73ecdfab0/index.html#L49)):_
Can we s/ng-show/ng-disabled/ here and below?

---

_[index.html, line 52 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8tIVEZ68hvbdheDrMN:-K8tIVE_8STeXIPMjUyw:-1150086323) ([raw file](https://github.com/jgraham/wptview/blob/e53190c9796468fc3dc3a04800fe8ff73ecdfab0/index.html#L52)):_
Not sure this needs a `for=` attribute at all.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by jgraham** [comment]
Just a couple of really trivial issues left, I think.

**Comment by udiboy1209** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[index.html, line 49 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8tIIV3qOY3AmV3k8E1:-K8weEcIFKLDhcu56olB:-499146009) ([raw file](https://github.com/jgraham/wptview/blob/e53190c9796468fc3dc3a04800fe8ff73ecdfab0/index.html#L49)):_
Done.

---

_[index.html, line 52 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K8tIVEZ68hvbdheDrMN:-K8wdm7opWbKGiJdr7L-:-623565034) ([raw file](https://github.com/jgraham/wptview/blob/e53190c9796468fc3dc3a04800fe8ff73ecdfab0/index.html#L52)):_
I guess it doesn't but this wasn't my change hence I'm not touching it. Should be done in another commit I believe.

---

_[logcruncher.js, line 55 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/68#-K80k31lnhS_eLYLpuqt:-K8weTEJ8xnh4eeCGeRq:-499146009) ([raw file](https://github.com/jgraham/wptview/blob/a6f0910968c88759d59691d8015ae9f94235ec22/logcruncher.js#L55)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by jgraham** [comment]
Needs a rebase onto latest master

**Comment by udiboy1209** [comment]
@jgraham rebased. Sorry didn't see it before. Would have done it. :stuck_out_tongue:

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/68)_

**Comment by jgraham** [comment]
Merged! Thanks for sticking with it!

**Pull request merged**
