### PR TITLE
Adding basic AngularJS code to display 40 results

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@jgraham, The code works! I hope it is structured correctly

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/5)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[index.html, line 26 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K4-wPuB7miEmVUgVyO1:-K4-wPuCkWS5d35gCqdQ:1456257158) ([raw file](https://github.com/jgraham/wptview/blob/08a37f99a894c2aebeec67ad523997b7ae4cfda7/index.html#L26)):_
Let's move all of this out into an external script now.

---

_[index.html, line 47 [r1]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K4-wcA2lC3ZU2jMh7TS:-K4-wcA3MtqWnvfWkvUE:2026658652) ([raw file](https://github.com/jgraham/wptview/blob/08a37f99a894c2aebeec67ad523997b7ae4cfda7/index.html#L47)):_
So it seems like the database should be exposed through an angular model rather than in the controller directly.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/5)_

**Comment by martiansideofthemoon** [comment]
@jgraham , Tried to emulate the stackoverflow question.

**Comment by jgraham** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

_[angular_scripts.js, line 14 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K43A-_s5NZpmFqw7d1j:-K43A-_tW8DVU0P70gn-:-88943712) ([raw file](https://github.com/jgraham/wptview/blob/7ad9ca058138b0aedc22138e403a95eacd9a0aa8/angular_scripts.js#L14)):_
Let's call this 'resultsModel' or something; the specific backend is an implementation detail.

---

_[angular_scripts.js, line 30 [r2]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K439d_udsxMrSdo-du5:-K439d_udsxMrSdo-du6:-1670093432) ([raw file](https://github.com/jgraham/wptview/blob/7ad9ca058138b0aedc22138e403a95eacd9a0aa8/angular_scripts.js#L30)):_
So this is still doing a bunch of db manipulation in the controller. I would expect the model to expose methods like addResultsFromLog and getResults and the controller to call those.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/5)_

**Comment by martiansideofthemoon** [comment]
@jgraham , Updated PR with flattened promises. Does it look good?

**Comment by jgraham** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[logcruncher.js, line 25 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K4Nt_jaIM3aElmlz0vs:-K4Nt_jbhbWs6K1imRCx:-1643721729) ([raw file](https://github.com/jgraham/wptview/blob/4c838de5f72f087ea72f41315bd61d38a1e92992/logcruncher.js#L25)):_
Extra space here

---

_[logcruncher.js, line 27 [r4]](https://reviewable.io:443/reviews/jgraham/wptview/5#-K4Ntds3v7m1QrgRqd-5:-K4Ntds3v7m1QrgRqd-6:2097897961) ([raw file](https://github.com/jgraham/wptview/blob/4c838de5f72f087ea72f41315bd61d38a1e92992/logcruncher.js#L27)):_
Remove

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/5)_

**Comment by jgraham** [comment]
Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wptview/5)_

**Pull request merged**
