### PR TITLE
Adding Travis CI

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
ref #56 . Importing commits from #55

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/wptview/116)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
@jgraham is this ok?

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[.travis.yml, line 9 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEBrawqnue1GorzXlrE:-KEBrawsZm_QY-YkjVvA:-1288575587) ([raw file](https://github.com/mozilla/wptview/blob/d0a0a61f151e4cfd9ff0a1c6be0eb0d5dc6c9835/.travis.yml#L9)):_
This doesn't seem right, see https://docs.travis-ci.com/user/encryption-keys/

---

_[bin/test_travis.sh, line 2 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEBs8eE1E4kreM1XDFP:-KEBs8eF-2sXpVxsw1C3:-849876782) ([raw file](https://github.com/mozilla/wptview/blob/d0a0a61f151e4cfd9ff0a1c6be0eb0d5dc6c9835/bin/test_travis.sh#L2)):_
You also want to check if `$TRAVIS_PULL_REQUEST` is set to `"false"` and if not then exit.

---

_[bin/test_travis.sh, line 12 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEBrCA2BhMUe1M14f0t:-KEBrCA2BhMUe1M14f0u:1016210808) ([raw file](https://github.com/mozilla/wptview/blob/d0a0a61f151e4cfd9ff0a1c6be0eb0d5dc6c9835/bin/test_travis.sh#L12)):_
I don't think any of this is actually needed, right? Just doing a git push (which is all we want) doesn't require configuring a username (I think).

---

_[bin/test_travis.sh, line 17 [r3]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEBrN_Rz5ouJ1MvcLtY:-KEBrN_S7HQDRahTHKZM:27634407) ([raw file](https://github.com/mozilla/wptview/blob/d0a0a61f151e4cfd9ff0a1c6be0eb0d5dc6c9835/bin/test_travis.sh#L17)):_
This doesn't do a force push, which the comment claims it does. `GH_TOKEN` is going to be undefined (that's the thing that you need to encrypt above).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/116)_

**Comment by udiboy1209** [comment]
This might help: https://gist.github.com/todvora/14cf2d21d37b9e72ecd5

**Comment by martiansideofthemoon** [comment]
@jgraham does this look better now? I used a personal token and generated the secure encrypted key using `travis encrypt GH_TOKEN=<my token>` inside the local clone of `mozilla/wptview`

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[bin/test_travis.sh, line 3 [r4]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEFrlo7Y-uIJWqiWvw5:-KEFrlo8imTV1FOHrqds:1742383620) ([raw file](https://github.com/mozilla/wptview/blob/943f8665cc3a74931d996e114a71026580688d1e/bin/test_travis.sh#L3)):_
This is exactly the wrong condition :) You don't want to run this on pull requests, but on changes to master once PRs are merged.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/116)_

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[bin/test_travis.sh, line 3 [r4]](https://reviewable.io:443/reviews/mozilla/wptview/116#-KEFrlo7Y-uIJWqiWvw5:-KEFxuJO5-66Qh_SUUcH:-1707554532) ([raw file](https://github.com/mozilla/wptview/blob/943f8665cc3a74931d996e114a71026580688d1e/bin/test_travis.sh#L3)):_
I think the syntax here is

```
if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
   exit
fi
```

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/116)_

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/116)_

**Pull request merged**
