### PR TITLE
Allow importing logs in test runner JSON format

### LINKED ISSUE #97: Consider consuming the w3c-test runner data format
http://w3c-test.org/tools/runner/index.html produces some kind of json. It might be nice to be able to consume it.

### PR DESCRIPTION
**Pull request by jgraham**
Fixes #97

[Review on Reviewable](https://reviewable.io/reviews/mozilla/wptview/98)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[logcruncher.js, line 23 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/98#-KBqxKe5tfbSmpMtG5Oy:-KBqt1XGdaLJgFw5OQKi:1755273361) ([raw file](https://github.com/mozilla/wptview/blob/9484e61efe3b4c573a4ebb6e57db4e3aaa616c0c/logcruncher.js#L23)):_
**nit**: missing `;`

---

_[logcruncher.js, line 48 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/98#-KBqx6ppht2kE2UBQfxP:-KBqx6pq78c7brZ9saAf:-1624614355) ([raw file](https://github.com/mozilla/wptview/blob/9484e61efe3b4c573a4ebb6e57db4e3aaa616c0c/logcruncher.js#L48)):_
Don't we need a test filter here as well?
**nit**: Maybe parseRunnerJSON for consistency?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/98)_

**Comment by martiansideofthemoon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/98)_

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[logcruncher.js, line 48 [r1]](https://reviewable.io:443/reviews/mozilla/wptview/98#-KBqx6ppht2kE2UBQfxP:-KBr2L67mva3Ai9E-7ov:-51194842) ([raw file](https://github.com/mozilla/wptview/blob/9484e61efe3b4c573a4ebb6e57db4e3aaa616c0c/logcruncher.js#L48)):_
No, because the `testFilter` is just to filter out non-result lines from the logs. In this case we are generating logs that only have result lines in the first place.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/98)_

**Comment by martiansideofthemoon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/wptview/98)_

**Pull request merged**
