### PR TITLE
Disable Import log button for repeated run name

### PR DESCRIPTION
**Pull request by CodeMaxx**
patch for #81 
@martiansideofthemoon @jgraham

[Review on Reviewable](https://reviewable.io/reviews/jgraham/wptview/83)

### CODE REVIEW

**Comment by CodeMaxx** [comment]
What else needs to be done in case of same run name?

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , I guess you could have asked the other contributor / me / @jgraham once before submitting a fix. "easy" bugs are meant to get newcomers involved. It isn't wrong to work on an "easy" bug, but it's wrong to submit a patch for an "easy" issue someone has promised to work on just 3 hours ago. I'm sorry I'll need to close this PR until the other contributor fails to do a good job.
In any case, you may update this PR. It doesn't work as expected. I'm getting two "Import" buttons, one getting disabled in the use case.

**Comment by CodeMaxx** [comment]
@martiansideofthemoon Sorry about that. I hadn't checked the issue before sending in the PR.
Also this is working completely fine on my machine. Can you please check again. Send me a screenshot of what you see on the webpage and also lines 48 through 53 of the index.html file.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , compare the diff of the PR with your commits. You can pull this PR using `git fetch <jgraham's repo remote> pull/ID/head:BRANCHNAME`

**Pull request closed without merging**
